# -*- coding: utf-8 -*-
"""efficeintNet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ibLkcW185pQhZGRQx5C9Wnm8ewWhFWNa
"""

import os
import time
import csv
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
from PIL import Image
import torchvision.transforms as T
from torchvision.models import efficientnet_b3, EfficientNet_B3_Weights
from torchvision.models.detection import FasterRCNN
from torchvision.models.detection.backbone_utils import BackboneWithFPN
from torchvision.models.detection.rpn import AnchorGenerator
from torchvision.ops import misc as misc_nn_ops
from torch.optim import SGD
from torch.optim.lr_scheduler import StepLR
import numpy as np
from sklearn.metrics import classification_report, roc_curve, auc, precision_recall_fscore_support, accuracy_score, confusion_matrix
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import seaborn as sns

# Set the path to your dataset
base_path = "/content/drive/MyDrive/final_dataset"
train_path = f"{base_path}/train/"
valid_path = f"{base_path}/valid/"

# Dataset class
class LunarDataset(Dataset):
    def __init__(self, csv_file, img_dir, transform=None):
        self.annotations = pd.read_csv(csv_file)
        self.img_dir = img_dir
        self.transform = transform
        self.classes = ['Crater', 'Boulder']  # Only foreground classes
        self.class_to_idx = {cls: idx + 1 for idx, cls in enumerate(self.classes)}  # Map to 1, 2 (0 is background)

    def __len__(self):
        return len(self.annotations['filename'].unique())

    def __getitem__(self, idx):
        img_name = self.annotations['filename'].unique()[idx]
        img_path = os.path.join(self.img_dir, img_name)
        image = Image.open(img_path).convert('RGB')

        # Filter out 'Plain surface' annotations
        img_annotations = self.annotations[self.annotations['filename'] == img_name]
        boxes = []
        labels = []
        for _, row in img_annotations.iterrows():
            class_name = row['class']
            if class_name in self.class_to_idx:  # Only include Crater and Boulder
                xmin, ymin, xmax, ymax = row[['xmin', 'ymin', 'xmax', 'ymax']]
                boxes.append([xmin, ymin, xmax, ymax])
                labels.append(self.class_to_idx[class_name])

        boxes = torch.as_tensor(boxes, dtype=torch.float32)
        labels = torch.as_tensor(labels, dtype=torch.int64)

        # Handle empty annotations (no foreground objects)
        if len(boxes) == 0:
            boxes = torch.zeros((0, 4), dtype=torch.float32)
            labels = torch.zeros(0, dtype=torch.int64)

        target = {
            'boxes': boxes,
            'labels': labels,
            'image_id': torch.tensor([idx]),
            'area': (boxes[:, 3] - boxes[:, 1]) * (boxes[:, 2] - boxes[:, 0]) if len(boxes) > 0 else torch.tensor([]),
            'iscrowd': torch.zeros((len(boxes),), dtype=torch.int64)
        }

        if self.transform:
            image = self.transform(image)

        return image, target, img_name

# Define EfficientNet-B3 Backbone
def get_efficientnet_backbone():
    backbone = efficientnet_b3(weights=EfficientNet_B3_Weights.IMAGENET1K_V1)
    features = backbone.features

    class EfficientNetBackbone(torch.nn.Module):
        def __init__(self, features):
            super().__init__()
            self.layer_2 = torch.nn.Sequential(*features[:3])
            self.layer_4 = torch.nn.Sequential(*features[3:5])
            self.layer_6 = torch.nn.Sequential(*features[5:7])
            self.layer_8 = torch.nn.Sequential(*features[7:9])

        def forward(self, x):
            outputs = {}
            x = self.layer_2(x)
            outputs['0'] = x
            x = self.layer_4(x)
            outputs['1'] = x
            x = self.layer_6(x)
            outputs['2'] = x
            x = self.layer_8(x)
            outputs['3'] = x
            return outputs

    device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
    custom_backbone = EfficientNetBackbone(features).to(device)

    return_layers = {
        'layer_2': '0',  # 32 channels
        'layer_4': '1',  # 96 channels
        'layer_6': '2',  # 232 channels
        'layer_8': '3'   # 1536 channels
    }

    backbone_with_fpn = BackboneWithFPN(
        backbone=custom_backbone,
        return_layers=return_layers,
        in_channels_list=[32, 96, 232, 1536],
        out_channels=256,
        norm_layer=misc_nn_ops.FrozenBatchNorm2d,
        extra_blocks=None
    ).to(device)

    return backbone_with_fpn

# Data transformations
train_transform = T.Compose([
    T.ToTensor(),
    T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

valid_transform = T.Compose([
    T.ToTensor(),
    T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# Create datasets
train_csv = train_path + "_annotations.csv"
valid_csv = valid_path + "_annotations.csv"

train_dataset = LunarDataset(csv_file=train_csv, img_dir=train_path, transform=train_transform)
valid_dataset = LunarDataset(csv_file=valid_csv, img_dir=valid_path, transform=valid_transform)

def collate_fn(batch):
    return tuple(zip(*batch))

train_loader = DataLoader(train_dataset, batch_size=4, shuffle=True, collate_fn=collate_fn)
valid_loader = DataLoader(valid_dataset, batch_size=4, shuffle=False, collate_fn=collate_fn)

# Custom anchor generator for 5 FPN levels
anchor_generator = AnchorGenerator(
    sizes=((16, 32, 64), (32, 64, 128), (64, 128, 256), (128, 256, 512), (256, 512, 1024)),
    aspect_ratios=((0.5, 1.0, 2.0),) * 5
)

# Create model
backbone = get_efficientnet_backbone()
model = FasterRCNN(
    backbone,
    num_classes=3,  # 2 classes (Crater, Boulder) + background
    min_size=600,
    max_size=1000,
    rpn_anchor_generator=anchor_generator,
    rpn_pre_nms_top_n_train=2000,
    rpn_pre_nms_top_n_test=1000,
    rpn_post_nms_top_n_train=2000,
    rpn_post_nms_top_n_test=1000,
    rpn_nms_thresh=0.7,
    rpn_fg_iou_thresh=0.7,
    rpn_bg_iou_thresh=0.3,
    box_score_thresh=0.01,
    box_nms_thresh=0.5,
    box_detections_per_img=300
)

# Move to GPU if available
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
model.to(device)

# Helper functions for evaluation
def compute_iou(box1, box2):
    """Compute IoU between two boxes [x1, y1, x2, y2]."""
    x1, y1, x2, y2 = box1
    x1_g, y1_g, x2_g, y2_g = box2

    x_left = max(x1, x1_g)
    y_top = max(y1, y1_g)
    x_right = min(x2, x2_g)
    y_bottom = min(y2, y2_g)

    if x_right < x_left or y_bottom < y_top:
        return 0.0

    intersection = (x_right - x_left) * (y_bottom - y_top)
    area1 = (x2 - x1) * (y2 - y1)
    area2 = (x2_g - x1_g) * (y2_g - y1_g)
    union = area1 + area2 - intersection

    return intersection / union if union > 0 else 0.0

def match_predictions_to_targets(preds, targets, iou_threshold=0.5):
    """Match predicted boxes to ground truth boxes based on IoU."""
    matched_preds, matched_labels = [], []
    for pred, target in zip(preds, targets):
        pred_boxes = pred['boxes'].cpu().numpy()
        pred_labels = pred['labels'].cpu().numpy()
        pred_scores = pred['scores'].cpu().numpy()
        gt_boxes = target['boxes'].cpu().numpy()
        gt_labels = target['labels'].cpu().numpy()

        if len(pred_boxes) == 0 or len(gt_boxes) == 0:
            continue

        # Compute IoU between all predicted and ground truth boxes
        ious = np.zeros((len(pred_boxes), len(gt_boxes)))
        for i, p_box in enumerate(pred_boxes):
            for j, g_box in enumerate(gt_boxes):
                iou = compute_iou(p_box, g_box)
                ious[i, j] = iou

        # Match predictions to ground truth with highest IoU
        used_gt = set()
        for i in np.argsort(pred_scores)[::-1]:
            if i >= len(pred_boxes):
                break
            max_iou_idx = np.argmax(ious[i])
            max_iou = ious[i, max_iou_idx]
            if max_iou >= iou_threshold and max_iou_idx not in used_gt:
                matched_preds.append(pred_labels[i])
                matched_labels.append(gt_labels[max_iou_idx])
                used_gt.add(max_iou_idx)

    return matched_preds, matched_labels

optimizer = SGD(model.parameters(), lr=0.0005, momentum=0.9, weight_decay=0.0005)
scheduler = StepLR(optimizer, step_size=3, gamma=0.1)

# Start timing for training
start_time = time.time()

# Training and Validation Loop
num_epochs = 20
train_losses, valid_losses = [], []
train_accuracies, valid_accuracies = [], []
valid_preds_all, valid_labels_all, valid_scores_all = [], [], []

# Create history dictionary to store all metrics
history = {
    'epoch': [],
    'train_loss': [],
    'valid_loss': [],
    'train_accuracy': [],
    'valid_accuracy': [],
    'train_precision': [],
    'train_recall': [],
    'train_f1': [],
    'valid_precision': [],
    'valid_recall': [],
    'valid_f1': []
}

for epoch in range(num_epochs):
    model.train()
    train_loss = 0.0
    train_preds, train_labels = [], []
    batch_count = 0

    for images, targets, _ in train_loader:
        images = list(image.to(device) for image in images)
        targets = [{k: v.to(device) for k, v in t.items()} for t in targets]

        loss_dict = model(images, targets)
        losses = sum(loss for loss in loss_dict.values())

        if not torch.isfinite(losses):
            print("Loss is not finite. Skipping batch.")
            continue

        train_loss += losses.item()
        batch_count += 1

        optimizer.zero_grad()
        losses.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=0.5)
        optimizer.step()

        with torch.no_grad():
            model.eval()
            preds = model(images)
            matched_preds, matched_labels = match_predictions_to_targets(preds, targets)
            train_preds.extend(matched_preds)
            train_labels.extend(matched_labels)
            model.train()

    train_loss = train_loss / batch_count if batch_count > 0 else 0.0
    train_losses.append(train_loss)

    # Calculate training metrics
    if len(train_labels) > 0:
        train_acc = sum(p == t for p, t in zip(train_preds, train_labels)) / len(train_labels)
        precision, recall, f1, _ = precision_recall_fscore_support(
            train_labels, train_preds, average='macro', zero_division=0
        )
    else:
        train_acc, precision, recall, f1 = 0.0, 0.0, 0.0, 0.0

    train_accuracies.append(train_acc)

    # Validation
    model.eval()
    valid_loss = 0.0
    valid_preds, valid_labels = [], []
    valid_scores = []
    valid_batch_count = 0

    with torch.no_grad():
        for images, targets, _ in valid_loader:
            images = list(image.to(device) for image in images)
            targets = [{k: v.to(device) for k, v in t.items()} for t in targets]

            # Switch to train mode for loss calculation
            model.train()
            loss_dict = model(images, targets)
            losses = sum(loss for loss in loss_dict.values())
            if not torch.isfinite(losses):
                print("Validation loss is not finite. Skipping batch.")
                continue
            valid_loss += losses.item()
            valid_batch_count += 1

            # Switch back to eval mode for predictions
            model.eval()
            preds = model(images)
            matched_preds, matched_labels = match_predictions_to_targets(preds, targets)
            valid_preds.extend(matched_preds)
            valid_labels.extend(matched_labels)
            for pred in preds:
                valid_scores.extend(pred['scores'].cpu().numpy())

    valid_loss = valid_loss / valid_batch_count if valid_batch_count > 0 else 0.0
    valid_losses.append(valid_loss)

    # Calculate validation metrics
    if len(valid_labels) > 0:
        valid_acc = sum(p == t for p, t in zip(valid_preds, valid_labels)) / len(valid_labels)
        val_precision, val_recall, val_f1, _ = precision_recall_fscore_support(
            valid_labels, valid_preds, average='macro', zero_division=0
        )
    else:
        valid_acc, val_precision, val_recall, val_f1 = 0.0, 0.0, 0.0, 0.0

    valid_accuracies.append(valid_acc)

    if epoch == num_epochs - 1:
        valid_preds_all = valid_preds
        valid_labels_all = valid_labels
        valid_scores_all = valid_scores

    # Update history
    history['epoch'].append(epoch+1)
    history['train_loss'].append(train_loss)
    history['valid_loss'].append(valid_loss)
    history['train_accuracy'].append(train_acc)
    history['valid_accuracy'].append(valid_acc)
    history['train_precision'].append(precision)
    history['train_recall'].append(recall)
    history['train_f1'].append(f1)
    history['valid_precision'].append(val_precision)
    history['valid_recall'].append(val_recall)
    history['valid_f1'].append(val_f1)

    print(f"Epoch [{epoch+1}/{num_epochs}]")
    print(f"Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.4f}")
    print(f"Valid Loss: {valid_loss:.4f}, Valid Acc: {valid_acc:.4f}")
    print(f"Train Precision: {precision:.4f}, Train Recall: {recall:.4f}, Train F1: {f1:.4f}")
    print(f"Valid Precision: {val_precision:.4f}, Valid Recall: {val_recall:.4f}, Valid F1: {val_f1:.4f}")

    scheduler.step()

# Calculate total training time
training_time = time.time() - start_time
print(f"Total training time: {training_time:.2f} seconds ({training_time/60:.2f} minutes)")

# Save the model
model_save_path = '/content/drive/MyDrive/models/efficientnet_b3_faster_rcnn2_model2.pth'
torch.save(model.state_dict(), model_save_path)
print(f"Model saved to {model_save_path}")

# Save history to CSV
history_path = '/content/drive/MyDrive/Required/efficientNet/model_training_history.csv'
with open(history_path, 'w', newline='') as csvfile:
    writer = csv.DictWriter(csvfile, fieldnames=history.keys())
    writer.writeheader()
    for i in range(len(history['epoch'])):
        row = {k: history[k][i] for k in history.keys()}
        writer.writerow(row)
print(f"Training history saved to {history_path}")

# Calculate overall metrics on validation set
if len(valid_labels_all) > 0:
    overall_accuracy = accuracy_score(valid_labels_all, valid_preds_all)
    precision, recall, f1, _ = precision_recall_fscore_support(
        valid_labels_all, valid_preds_all, average='macro', zero_division=0
    )
    class_report = classification_report(
        valid_labels_all, valid_preds_all, target_names=train_dataset.classes, zero_division=0
    )

    print("\nOverall Metrics:")
    print(f"Accuracy: {overall_accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall: {recall:.4f}")
    print(f"F1 Score: {f1:.4f}")

    print("\nClassification Report:")
    print(class_report)

    # Calculate class-wise metrics
    class_precision, class_recall, class_f1, _ = precision_recall_fscore_support(
        valid_labels_all, valid_preds_all, labels=[1, 2], average=None, zero_division=0
    )

    # Print class-wise metrics
    print("\nClass-wise Metrics:")
    for i, class_name in enumerate(train_dataset.classes):
        print(f"{class_name}:")
        print(f"  Precision: {class_precision[i]:.4f}")
        print(f"  Recall: {class_recall[i]:.4f}")
        print(f"  F1 Score: {class_f1[i]:.4f}")

    # Create confusion matrix
    cm = confusion_matrix(valid_labels_all, valid_preds_all)
    plt.figure(figsize=(10, 8))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=train_dataset.classes,
                yticklabels=train_dataset.classes)
    plt.xlabel('Predicted')
    plt.ylabel('Ground Truth')
    plt.title('Confusion Matrix')
    plt.savefig('/content/drive/MyDrive/Required/efficientNet/confusion_matrix.png')
    plt.show()

# Training vs Validation Accuracy Graph
plt.figure(figsize=(12, 8))
plt.plot(history['epoch'], history['train_accuracy'], label='Training Accuracy', color='green', marker='o')
plt.plot(history['epoch'], history['valid_accuracy'], label='Validation Accuracy', color='orange', marker='o')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.title('Training vs Validation Accuracy')
plt.legend()
plt.grid(True)
plt.savefig('/content/drive/MyDrive/Required/efficientNet/accuracy_comparison.png')
plt.show()

# Training vs Validation Loss Graph
plt.figure(figsize=(12, 8))
plt.plot(history['epoch'], history['train_loss'], label='Training Loss', color='green', marker='o')
plt.plot(history['epoch'], history['valid_loss'], label='Validation Loss', color='orange', marker='o')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Training vs Validation Loss')
plt.legend()
plt.grid(True)
plt.savefig('/content/drive/MyDrive/Required/efficientNet/loss_comparison.png')
plt.show()

# Precision-Recall Curves
plt.figure(figsize=(12, 8))
plt.plot(history['epoch'], history['train_precision'], label='Training Precision', color='blue', marker='o')
plt.plot(history['epoch'], history['valid_precision'], label='Validation Precision', color='red', marker='o')
plt.plot(history['epoch'], history['train_recall'], label='Training Recall', color='cyan', marker='^')
plt.plot(history['epoch'], history['valid_recall'], label='Validation Recall', color='magenta', marker='^')
plt.xlabel('Epoch')
plt.ylabel('Score')
plt.title('Precision and Recall over Epochs')
plt.legend()
plt.grid(True)
plt.savefig('/content/drive/MyDrive/Required/efficientNet/precision_recall_comparison.png')
plt.show()

# F1 Score Comparison
plt.figure(figsize=(12, 8))
plt.plot(history['epoch'], history['train_f1'], label='Training F1', color='green', marker='o')
plt.plot(history['epoch'], history['valid_f1'], label='Validation F1', color='orange', marker='o')
plt.xlabel('Epoch')
plt.ylabel('F1 Score')
plt.title('Training vs Validation F1 Score')
plt.legend()
plt.grid(True)
plt.savefig('/content/drive/MyDrive/Required/efficientNet/f1_comparison.png')
plt.show()

# Function to visualize predictions on test images
def visualize_predictions(model, data_loader, class_names, device, score_threshold=0.5, max_images=5):
    """
    Visualize model predictions on images from the data loader
    """
    model.eval()
    results = []

    with torch.no_grad():
        for i, (images, targets, img_names) in enumerate(data_loader):
            if i >= max_images:
                break

            images_list = list(img.to(device) for img in images)
            targets_list = [{k: v.to(device) for k, v in t.items()} for t in targets]

            # Run inference
            outputs = model(images_list)

            # Store results
            for j, (img, target, prediction, img_name) in enumerate(zip(images_list, targets_list, outputs, img_names)):
                results.append({
                    'image': img.cpu(),
                    'target': target,
                    'prediction': prediction,
                    'image_name': img_name
                })

    # Visualize results
    for idx, result in enumerate(results):
        img = result['image'].permute(1, 2, 0).numpy()
        img = img * np.array([0.229, 0.224, 0.225]) + np.array([0.485, 0.456, 0.406])
        img = np.clip(img, 0, 1)

        # Create figure with 2 subplots (ground truth and predictions)
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(20, 10))

        # Ground Truth
        ax1.imshow(img)
        gt_boxes = result['target']['boxes'].cpu().numpy()
        gt_labels = result['target']['labels'].cpu().numpy()

        for box, label in zip(gt_boxes, gt_labels):
            x1, y1, x2, y2 = box
            rect = patches.Rectangle((x1, y1), x2-x1, y2-y1, linewidth=2, edgecolor='g', facecolor='none')
            ax1.add_patch(rect)
            ax1.text(x1, y1-10, class_names[label-1], color='white', fontsize=12,
                    bbox=dict(facecolor='g', alpha=0.7))

        ax1.set_title(f"Ground Truth - {result['image_name']}")
        ax1.axis('off')

        # Predictions
        ax2.imshow(img)
        pred_boxes = result['prediction']['boxes'].cpu().numpy()
        pred_labels = result['prediction']['labels'].cpu().numpy()
        pred_scores = result['prediction']['scores'].cpu().numpy()

        # Filter by score threshold
        valid_indices = pred_scores >= score_threshold
        filtered_boxes = pred_boxes[valid_indices]
        filtered_labels = pred_labels[valid_indices]
        filtered_scores = pred_scores[valid_indices]

        for box, label, score in zip(filtered_boxes, filtered_labels, filtered_scores):
            x1, y1, x2, y2 = box
            rect = patches.Rectangle((x1, y1), x2-x1, y2-y1, linewidth=2, edgecolor='r', facecolor='none')
            ax2.add_patch(rect)
            ax2.text(x1, y1-10, f"{class_names[label-1]}: {score:.2f}", color='white', fontsize=12,
                    bbox=dict(facecolor='r', alpha=0.7))

        ax2.set_title(f"Predictions (score ≥ {score_threshold}) - {result['image_name']}")
        ax2.axis('off')

        plt.tight_layout()
        plt.savefig(f"/content/drive/MyDrive/Required/efficientNet/prediction_visualization_{idx}.png")
        plt.show()

        # Print detection metrics for this image
        matched_preds, matched_labels = match_predictions_to_targets(
            [result['prediction']], [result['target']])

        if matched_labels:
            acc = sum(p == t for p, t in zip(matched_preds, matched_labels)) / len(matched_labels)
            print(f"Image {idx+1} ({result['image_name']}) - Detection Accuracy: {acc:.4f}")
        else:
            print(f"Image {idx+1} ({result['image_name']}) - No matched predictions")

        # Print counts of each class
        pred_class_counts = {
            class_name: sum(filtered_labels == class_idx+1)
            for class_idx, class_name in enumerate(class_names)
        }
        gt_class_counts = {
            class_name: sum(gt_labels == class_idx+1)
            for class_idx, class_name in enumerate(class_names)
        }

        print(f"Ground Truth: {gt_class_counts}")
        print(f"Predictions: {pred_class_counts}")
        print("-" * 50)

# Function to evaluate on test images
def evaluate_on_test_images(model, test_dir, test_csv, class_names, device, score_threshold=0.5, max_images=5):
    """
    Load test images and evaluate model performance
    """
    # Create test dataset and loader
    test_transform = T.Compose([
        T.ToTensor(),
        T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])

    test_dataset = LunarDataset(csv_file=test_csv, img_dir=test_dir, transform=test_transform)
    test_loader = DataLoader(test_dataset, batch_size=1, shuffle=False, collate_fn=collate_fn)

    # Evaluate and visualize
    visualize_predictions(
        model=model,
        data_loader=test_loader,
        class_names=class_names,
        device=device,
        score_threshold=score_threshold,
        max_images=max_images
    )

    # Calculate metrics on test set
    model.eval()
    all_preds = []
    all_targets = []
    all_scores = []

    with torch.no_grad():
        for images, targets, _ in test_loader:
            images = list(img.to(device) for img in images)
            targets = [{k: v.to(device) for k, v in t.items()} for t in targets]

            outputs = model(images)

            # Match predictions to ground truth
            matched_preds, matched_targets = match_predictions_to_targets(outputs, targets)
            all_preds.extend(matched_preds)
            all_targets.extend(matched_targets)

            # Collect scores
            for output in outputs:
                all_scores.extend(output['scores'].cpu().numpy())

    # Calculate and print metrics
    if len(all_targets) > 0:
        accuracy = accuracy_score(all_targets, all_preds)
        precision, recall, f1, _ = precision_recall_fscore_support(
            all_targets, all_preds, average='macro', zero_division=0
        )

        print("\nTest Set Metrics:")
        print(f"Accuracy: {accuracy:.4f}")
        print(f"Precision: {precision:.4f}")
        print(f"Recall: {recall:.4f}")
        print(f"F1 Score: {f1:.4f}")

        # Classification report
        print("\nTest Set Classification Report:")
        print(classification_report(all_targets, all_preds, target_names=class_names, zero_division=0))
    else:
        print("No matched predictions in test set")

# Run evaluation on validation set for visualization
print("\nVisualizing predictions on validation set:")
visualize_predictions(
    model=model,
    data_loader=valid_loader,
    class_names=train_dataset.classes,
    device=device,
    score_threshold=0.5,
    max_images=5
)