# -*- coding: utf-8 -*-
"""efficent-net with attetion layer .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uPocB3Q7z7KhDi_Ck_wXtBC-IJ2x7ewj
"""

import os
import time
import csv
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from PIL import Image
import torchvision.transforms as T
from torchvision.models import efficientnet_b3, EfficientNet_B3_Weights
from torchvision.models.detection import FasterRCNN
from torchvision.models.detection.backbone_utils import BackboneWithFPN
from torchvision.models.detection.rpn import AnchorGenerator
from torchvision.ops import misc as misc_nn_ops
from torch.optim import SGD, AdamW
from torch.optim.lr_scheduler import StepLR
import numpy as np
from sklearn.metrics import classification_report, roc_curve, auc, precision_recall_fscore_support, accuracy_score, confusion_matrix
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import seaborn as sns

import pandas as pd
import torch
from torch.utils.data import Dataset
from PIL import Image
import os

class LunarDataset(Dataset):
    def __init__(self, csv_file, img_dir, transform=None):
        try:
            self.annotations = pd.read_csv(csv_file)
        except Exception as e:
            raise ValueError(f"Failed to load CSV file {csv_file}: {e}")

        self.img_dir = img_dir
        self.transform = transform
        self.classes = ['Crater', 'Boulder']
        self.class_to_idx = {cls: idx + 1 for idx, cls in enumerate(self.classes)}  # Map to 1, 2 (0 is background)

        # Get unique image filenames and filter out images with no valid annotations
        self.image_names = self.annotations['filename'].unique()
        self.valid_images = []
        for img_name in self.image_names:
            img_annotations = self.annotations[self.annotations['filename'] == img_name]
            valid_annotations = img_annotations[img_annotations['class'].isin(self.classes)]
            has_valid_box = False
            for _, row in valid_annotations.iterrows():
                xmin, ymin, xmax, ymax = row[['xmin', 'ymin', 'xmax', 'ymax']]
                if (isinstance(xmin, (int, float)) and isinstance(ymin, (int, float)) and
                        isinstance(xmax, (int, float)) and isinstance(ymax, (int, float)) and
                        xmin < xmax and ymin < ymax):
                    has_valid_box = True
                    break
            if has_valid_box:
                img_path = os.path.join(self.img_dir, img_name)
                if os.path.exists(img_path):
                    self.valid_images.append(img_name)
                else:
                    print(f"Skipping {img_name}: Image file missing")
            else:
                print(f"Skipping {img_name}: No valid Crater or Boulder annotations")

        if not self.valid_images:
            raise ValueError(f"No valid images with Crater or Boulder annotations in {csv_file}")

        print(f"Dataset {csv_file}: {len(self.valid_images)} valid images")

    def __len__(self):
        return len(self.valid_images)

    def __getitem__(self, idx):
        img_name = self.valid_images[idx]
        img_path = os.path.join(self.img_dir, img_name)
        try:
            image = Image.open(img_path).convert('RGB')
        except Exception as e:
            print(f"Error loading image {img_name}: {e}")
            image = Image.new('RGB', (640, 640), color='black')
            target = {
                'boxes': torch.zeros((0, 4), dtype=torch.float32),
                'labels': torch.zeros(0, dtype=torch.int64),
                'image_id': torch.tensor([idx]),
                'area': torch.tensor([]),
                'iscrowd': torch.zeros((0,), dtype=torch.int64)
            }
            if self.transform:
                image = self.transform(image)
            return image, target, img_name

        img_annotations = self.annotations[self.annotations['filename'] == img_name]
        boxes = []
        labels = []
        for _, row in img_annotations.iterrows():
            class_name = row['class']
            if class_name in self.class_to_idx:
                xmin, ymin, xmax, ymax = row[['xmin', 'ymin', 'xmax', 'ymax']]
                if (isinstance(xmin, (int, float)) and isinstance(ymin, (int, float)) and
                        isinstance(xmax, (int, float)) and isinstance(ymax, (int, float)) and
                        xmin < xmax and ymin < ymax):
                    boxes.append([xmin, ymin, xmax, ymax])
                    labels.append(self.class_to_idx[class_name])
                else:
                    print(f"Invalid box for {img_name}, class {class_name}: {xmin, ymin, xmax, ymax}")

        boxes = torch.as_tensor(boxes, dtype=torch.float32)
        labels = torch.as_tensor(labels, dtype=torch.int64)

        if len(boxes) == 0:
            print(f"Warning: Empty target for {img_name} after processing")
            boxes = torch.zeros((0, 4), dtype=torch.float32)
            labels = torch.zeros(0, dtype=torch.int64)

        target = {
            'boxes': boxes,
            'labels': labels,
            'image_id': torch.tensor([idx]),
            'area': (boxes[:, 3] - boxes[:, 1]) * (boxes[:, 2] - boxes[:, 0]) if len(boxes) > 0 else torch.tensor([]),
            'iscrowd': torch.zeros((len(boxes),), dtype=torch.int64)
        }

        if self.transform:
            image = self.transform(image)

        return image, target, img_name

# =====================================================================
# MULTI-SCALE ATTENTION MODULE
# =====================================================================

class GumbelSigmoid(nn.Module):
    """Gumbel Sigmoid activation for differentiable discrete sampling"""
    def __init__(self, temperature=1.0):
        super().__init__()
        self.temperature = temperature

    def forward(self, logits):
        noise = torch.rand_like(logits)
        noise = -torch.log(-torch.log(noise + 1e-20) + 1e-20)
        return torch.sigmoid((logits + noise) / self.temperature)

class MultiScaleAttention(nn.Module):
    """Multi-Scale Attention module for focusing on relevant features at different scales"""
    def __init__(self, num_slots, feature_dim, attn_temperature=0.5, gumbel_temperature=0.5, dropout_rate=0.1):
        super(MultiScaleAttention, self).__init__()
        self.num_slots = num_slots
        self.feature_dim = feature_dim
        self.attn_temperature = attn_temperature
        self.dropout_rate = dropout_rate

        # Attention components
        self.query_proj = nn.Linear(feature_dim, feature_dim)
        # Change here: The in_channels must match the output channels of the fpn_convs layers
        self.key_value_projs = nn.ModuleList([nn.Conv2d(feature_dim, 2 * feature_dim, kernel_size=1)
                                             for _ in range(4)])

        # Learnable scale embeddings
        self.scale_embeddings = nn.ParameterList([
            nn.Parameter(torch.randn(feature_dim)) for _ in range(4)
        ])

        # Scale fusion weights
        self.scale_fusion_weights = nn.ParameterList([
            nn.Parameter(torch.randn(feature_dim, feature_dim)) for _ in range(4)
        ])

        self.gumbel_sigmoid = GumbelSigmoid(temperature=gumbel_temperature)
        self.dropout = nn.Dropout(dropout_rate)

        # MLP for slot updates
        self.mlp = nn.Sequential(
            nn.Linear(feature_dim, feature_dim * 2),
            nn.ReLU(),
            nn.Linear(feature_dim * 2, feature_dim)
        )

        # Mask decoder for visualization
        self.mask_decoder = nn.Linear(feature_dim, 128 * 128)
        self.layer_norm = nn.LayerNorm(feature_dim)

    def forward(self, features, slots):
        """
        Args:
            features: List of feature maps from different scales
            slots: [num_slots, feature_dim] attention slots
        Returns:
            Updated slots and attention masks
        """
        all_attended = []
        slots_norm = self.layer_norm(slots)
        queries = self.query_proj(slots_norm)  # [num_slots, feature_dim]

        for idx, feature_map in enumerate(features):
            B, C, H, W = feature_map.shape
            # Project feature map to keys and values
            proj = self.key_value_projs[idx](feature_map)  # [B, 2*feature_dim, H, W]
            keys, values = torch.split(proj, self.feature_dim, dim=1)

            # Reshape for attention
            keys = keys.permute(0, 2, 3, 1).reshape(B, H*W, self.feature_dim)  # [B, H*W, feature_dim]
            values = values.permute(0, 2, 3, 1).reshape(B, H*W, self.feature_dim)  # [B, H*W, feature_dim]

            # Scale-specific gating
            logits = self.query_proj(queries) + self.scale_embeddings[idx]
            gates = self.gumbel_sigmoid(logits)  # [num_slots, feature_dim]

            # Compute attention
            queries = self.query_proj(queries) * gates
            queries = queries + self.scale_embeddings[idx]

            # Compute attention
            attn_logits = torch.matmul(queries, keys.transpose(-2, -1))  # [num_slots, H*W]
            attn_logits = attn_logits / (self.attn_temperature * torch.sqrt(torch.tensor(self.feature_dim, dtype=torch.float32)))
            attn_weights = F.softmax(attn_logits, dim=-1)

            # Apply dropout (gating is already applied)
            attn_weights = self.dropout(attn_weights)

            # Attend to values
            attended = torch.matmul(attn_weights, values)  # [num_slots, feature_dim]

            # Scale-specific fusion
            fused = torch.matmul(attended, self.scale_fusion_weights[idx])
            all_attended.append(fused)

        # Combine attended features from all scales
        fused = torch.stack(all_attended).sum(dim=0)
        fused_norm = self.layer_norm(fused)

        # Update slots with MLP
        updated_slots = slots + self.mlp(fused_norm)

        # Decode masks for visualization (optional, can be used during training)
        masks = self.mask_decoder(updated_slots)
        masks = masks.reshape(-1, 128, 128)
        masks = torch.sigmoid(masks)

        return updated_slots, masks

class EfficientNetWithAttention(nn.Module):
    def __init__(self, num_slots=10, feature_dim=256):
        super(EfficientNetWithAttention, self).__init__()
        # Load EfficientNet-B3 backbone
        backbone = efficientnet_b3(weights=EfficientNet_B3_Weights.IMAGENET1K_V1)
        features = backbone.features

        # Create feature extraction layers
        self.layer1 = nn.Sequential(*features[:3])   # 32 channels
        self.layer2 = nn.Sequential(*features[3:5])  # 96 channels
        self.layer3 = nn.Sequential(*features[5:7])  # 232 channels
        self.layer4 = nn.Sequential(*features[7:9])  # 1536 channels

        # Initialize attention slots
        self.num_slots = num_slots
        self.feature_dim = feature_dim
        self.slots = nn.Parameter(torch.randn(num_slots, feature_dim))

        # Multi-scale attention module
        self.attention = MultiScaleAttention(
            num_slots=num_slots,
            feature_dim=feature_dim,
            attn_temperature=0.5,
            gumbel_temperature=0.5,
            dropout_rate=0.1
        )

        # FPN layers
        self.fpn_convs = nn.ModuleList([
            nn.Conv2d(32, feature_dim, kernel_size=1),
            nn.Conv2d(96, feature_dim, kernel_size=1),
            nn.Conv2d(232, feature_dim, kernel_size=1),
            nn.Conv2d(1536, feature_dim, kernel_size=1)
        ])

    def forward(self, x):
        # Extract features at different scales
        x1 = self.layer1(x)  # 32 channels
        x2 = self.layer2(x1)  # 96 channels
        x3 = self.layer3(x2)  # 232 channels
        x4 = self.layer4(x3)  # 1536 channels

        # Project features to common dimension
        p1 = self.fpn_convs[0](x1)
        p2 = self.fpn_convs[1](x2)
        p3 = self.fpn_convs[2](x3)
        p4 = self.fpn_convs[3](x4)

        # Apply attention to learn important features
        features = [p1, p2, p3, p4]
        updated_slots, attention_masks = self.attention(features, self.slots)

        # Return as dictionary for FPN
        # Return the features with correct keys for FasterRCNN
        return {
            '0': p1,  # Output from layer1
            '1': p2,  # Output from layer2
            '2': p3,  # Output from layer3
            '3': p4   # Output from layer4
        }

class AttentionEnhancedFPN(nn.Module):
    def __init__(self, backbone, in_channels_list, out_channels):
        super(AttentionEnhancedFPN, self).__init__()
        self.backbone = backbone
        self.out_channels = out_channels  # This is needed for FasterRCNN to work

        # Feature Pyramid Network (FPN)
        self.inner_blocks = nn.ModuleList()
        self.layer_blocks = nn.ModuleList()

        for in_channels in in_channels_list:
            self.inner_blocks.append(nn.Conv2d(in_channels, out_channels, 1))
            self.layer_blocks.append(nn.Conv2d(out_channels, out_channels, 3, padding=1))

        # Extra layer for highest level
        self.extra_blocks = nn.MaxPool2d(1, stride=2)

    def forward(self, x):
        # Get multi-scale features from the backbone
        features = self.backbone(x)

        # Apply FPN
        results = []
        last_inner = self.inner_blocks[-1](features['3'])
        results.append(self.layer_blocks[-1](last_inner))

        for idx in range(len(self.inner_blocks)-2, -1, -1):
            inner_lateral = self.inner_blocks[idx](features[str(idx)])

            # Upsample and add
            feat_shape = inner_lateral.shape[-2:]
            inner_top_down = F.interpolate(last_inner, size=feat_shape, mode="nearest")
            last_inner = inner_lateral + inner_top_down
            results.insert(0, self.layer_blocks[idx](last_inner))

        # Add extra layer (P6)
        results.append(self.extra_blocks(results[-1]))

        # Named results for detector
        names = ['p2', 'p3', 'p4', 'p5', 'p6']
        return {name: result for name, result in zip(names, results)}

def build_crater_detection_model(num_classes=3, num_slots=10, feature_dim=256):
    # [Your existing build_crater_detection_model function remains unchanged]
    backbone = EfficientNetWithAttention(num_slots=num_slots, feature_dim=feature_dim)
    in_channels_list = [feature_dim, feature_dim, feature_dim, feature_dim]
    fpn = AttentionEnhancedFPN(backbone, in_channels_list, feature_dim)
    anchor_generator = AnchorGenerator(
        sizes=((16, 32, 64), (32, 64, 128), (64, 128, 256), (128, 256, 512), (256, 512, 1024)),
        aspect_ratios=((0.5, 1.0, 2.0),) * 5
    )
    model = FasterRCNN(
        backbone=fpn,
        num_classes=num_classes,
        min_size=600,
        max_size=1000,
        rpn_anchor_generator=anchor_generator,
        rpn_pre_nms_top_n_train=2000,
        rpn_pre_nms_top_n_test=1000,
        rpn_post_nms_top_n_train=2000,
        rpn_post_nms_top_n_test=1000,
        rpn_nms_thresh=0.7,
        rpn_fg_iou_thresh=0.7,
        rpn_bg_iou_thresh=0.3,
        box_score_thresh=0.05,
        box_nms_thresh=0.5,
        box_detections_per_img=300
    )
    return model

# =====================================================================
# EVALUATION FUNCTIONS
# =====================================================================

def compute_iou(box1, box2):
    """Compute IoU between two boxes [x1, y1, x2, y2]."""
    x1, y1, x2, y2 = box1
    x1_g, y1_g, x2_g, y2_g = box2

    x_left = max(x1, x1_g)
    y_top = max(y1, y1_g)
    x_right = min(x2, x2_g)
    y_bottom = min(y2, y2_g)

    if x_right < x_left or y_bottom < y_top:
        return 0.0

    intersection = (x_right - x_left) * (y_bottom - y_top)
    area1 = (x2 - x1) * (y2 - y1)
    area2 = (x2_g - x1_g) * (y2_g - y1_g)
    union = area1 + area2 - intersection

    return intersection / union if union > 0 else 0.0

def match_predictions_to_targets(preds, targets, iou_threshold=0.5):
    """Match predicted boxes to ground truth boxes based on IoU."""
    matched_preds, matched_labels = [], []
    for pred, target in zip(preds, targets):
        pred_boxes = pred['boxes'].cpu().numpy()
        pred_labels = pred['labels'].cpu().numpy()
        pred_scores = pred['scores'].cpu().numpy()
        gt_boxes = target['boxes'].cpu().numpy()
        gt_labels = target['labels'].cpu().numpy()

        if len(pred_boxes) == 0 or len(gt_boxes) == 0:
            continue

        # Compute IoU between all predicted and ground truth boxes
        ious = np.zeros((len(pred_boxes), len(gt_boxes)))
        for i, p_box in enumerate(pred_boxes):
            for j, g_box in enumerate(gt_boxes):
                iou = compute_iou(p_box, g_box)
                ious[i, j] = iou

        # Match predictions to ground truth with highest IoU
        used_gt = set()
        for i in np.argsort(pred_scores)[::-1]:
            if i >= len(pred_boxes):
                break
            max_iou_idx = np.argmax(ious[i])
            max_iou = ious[i, max_iou_idx]
            if max_iou >= iou_threshold and max_iou_idx not in used_gt:
                matched_preds.append(pred_labels[i])
                matched_labels.append(gt_labels[max_iou_idx])
                used_gt.add(max_iou_idx)

    return matched_preds, matched_labels

# =====================================================================
# VISUALIZATION FUNCTIONS
# =====================================================================

def visualize_predictions(model, data_loader, class_names, device, score_threshold=0.5, max_images=5, save_dir=''):
    """Visualize model predictions on images from the data loader"""
    model.eval()
    results = []

    with torch.no_grad():
        for i, (images, targets, img_names) in enumerate(data_loader):
            if i >= max_images:
                break

            images_list = list(img.to(device) for img in images)
            targets_list = [{k: v.to(device) for k, v in t.items()} for t in targets]

            # Run inference
            outputs = model(images_list)

            # Store results
            for j, (img, target, prediction, img_name) in enumerate(zip(images_list, targets_list, outputs, img_names)):
                results.append({
                    'image': img.cpu(),
                    'target': target,
                    'prediction': prediction,
                    'image_name': img_name
                })

    # Visualize results
    for idx, result in enumerate(results):
        img = result['image'].permute(1, 2, 0).numpy()
        img = img * np.array([0.229, 0.224, 0.225]) + np.array([0.485, 0.456, 0.406])
        img = np.clip(img, 0, 1)

        # Create figure with 2 subplots (ground truth and predictions)
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(20, 10))

        # Ground Truth
        ax1.imshow(img)
        gt_boxes = result['target']['boxes'].cpu().numpy()
        gt_labels = result['target']['labels'].cpu().numpy()

        for box, label in zip(gt_boxes, gt_labels):
            x1, y1, x2, y2 = box
            rect = patches.Rectangle((x1, y1), x2-x1, y2-y1, linewidth=2, edgecolor='g', facecolor='none')
            ax1.add_patch(rect)
            ax1.text(x1, y1-10, class_names[label-1], color='white', fontsize=12,
                    bbox=dict(facecolor='g', alpha=0.7))

        ax1.set_title(f"Ground Truth - {result['image_name']}")
        ax1.axis('off')

        # Predictions
        ax2.imshow(img)
        pred_boxes = result['prediction']['boxes'].cpu().numpy()
        pred_labels = result['prediction']['labels'].cpu().numpy()
        pred_scores = result['prediction']['scores'].cpu().numpy()

        # Filter by score threshold
        valid_indices = pred_scores >= score_threshold
        filtered_boxes = pred_boxes[valid_indices]
        filtered_labels = pred_labels[valid_indices]
        filtered_scores = pred_scores[valid_indices]

        for box, label, score in zip(filtered_boxes, filtered_labels, filtered_scores):
            x1, y1, x2, y2 = box
            rect = patches.Rectangle((x1, y1), x2-x1, y2-y1, linewidth=2, edgecolor='r', facecolor='none')
            ax2.add_patch(rect)
            ax2.text(x1, y1-10, f"{class_names[label-1]}: {score:.2f}", color='white', fontsize=12,
                    bbox=dict(facecolor='r', alpha=0.7))

        ax2.set_title(f"Predictions (score ≥ {score_threshold}) - {result['image_name']}")
        ax2.axis('off')

        plt.tight_layout()
        save_path = os.path.join(save_dir, f"prediction_visualization_{idx}.png")
        plt.savefig(save_path)
        plt.close()

        # Print detection metrics for this image
        matched_preds, matched_labels = match_predictions_to_targets(
            [result['prediction']], [result['target']])

        if matched_labels:
            acc = sum(p == t for p, t in zip(matched_preds, matched_labels)) / len(matched_labels)
            print(f"Image {idx+1} ({result['image_name']}) - Detection Accuracy: {acc:.4f}")
        else:
            print(f"Image {idx+1} ({result['image_name']}) - No matched predictions")

        # Print counts of each class
        pred_class_counts = {
            class_name: sum(filtered_labels == class_idx+1)
            for class_idx, class_name in enumerate(class_names)
        }
        gt_class_counts = {
            class_name: sum(gt_labels == class_idx+1)
            for class_idx, class_name in enumerate(class_names)
        }

        print(f"Ground Truth: {gt_class_counts}")
        print(f"Predictions: {pred_class_counts}")
        print("-" * 50)

# =====================================================================
# PLOT METRICS FUNCTIONS
# =====================================================================

def plot_metrics(history, save_dir):
    """Plot and save training metrics"""
    # Training vs Validation Accuracy
    plt.figure(figsize=(12, 8))
    plt.plot(history['epoch'], history['train_accuracy'], label='Training Accuracy', color='green', marker='o')
    plt.plot(history['epoch'], history['valid_accuracy'], label='Validation Accuracy', color='orange', marker='o')
    plt.xlabel('Epoch')
    plt.ylabel('Accuracy')
    plt.title('Training vs Validation Accuracy')
    plt.legend()
    plt.grid(True)
    plt.savefig(os.path.join(save_dir, 'accuracy_comparison.png'))
    plt.close()

    # Training vs Validation Loss
    plt.figure(figsize=(12, 8))
    plt.plot(history['epoch'], history['train_loss'], label='Training Loss', color='green', marker='o')
    plt.plot(history['epoch'], history['valid_loss'], label='Validation Loss', color='orange', marker='o')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.title('Training vs Validation Loss')
    plt.legend()
    plt.grid(True)
    plt.savefig(os.path.join(save_dir, 'loss_comparison.png'))
    plt.close()

    # Precision-Recall Curves
    plt.figure(figsize=(12, 8))
    plt.plot(history['epoch'], history['train_precision'], label='Training Precision', color='blue', marker='o')
    plt.plot(history['epoch'], history['valid_precision'], label='Validation Precision', color='red', marker='o')
    plt.plot(history['epoch'], history['train_recall'], label='Training Recall', color='cyan', marker='^')
    plt.plot(history['epoch'], history['valid_recall'], label='Validation Recall', color='magenta', marker='^')
    plt.xlabel('Epoch')
    plt.ylabel('Score')
    plt.title('Precision and Recall over Epochs')
    plt.legend()
    plt.grid(True)
    plt.savefig(os.path.join(save_dir, 'precision_recall_comparison.png'))
    plt.close()

    # F1 Score Comparison
    plt.figure(figsize=(12, 8))
    plt.plot(history['epoch'], history['train_f1'], label='Training F1', color='green', marker='o')
    plt.plot(history['epoch'], history['valid_f1'], label='Validation F1', color='orange', marker='o')
    plt.xlabel('Epoch')
    plt.ylabel('F1 Score')
    plt.title('Training vs Validation F1 Score')
    plt.legend()
    plt.grid(True)
    plt.savefig(os.path.join(save_dir, 'f1_comparison.png'))
    plt.close()

# =====================================================================
# CONFUSION MATRIX FUNCTION
# =====================================================================

def plot_confusion_matrix(valid_labels_all, valid_preds_all, class_names, save_dir):
    """Create and save confusion matrix visualization"""
    cm = confusion_matrix(valid_labels_all, valid_preds_all)
    plt.figure(figsize=(10, 8))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=class_names,
                yticklabels=class_names)
    plt.xlabel('Predicted')
    plt.ylabel('Ground Truth')
    plt.title('Confusion Matrix')
    plt.savefig(os.path.join(save_dir, 'confusion_matrix.png'))
    plt.close()

def train_and_evaluate(base_path, output_dir, num_epochs=20, batch_size=4, num_slots=10, feature_dim=256):
    """Train and evaluate the model, saving results to output_dir"""
    os.makedirs(output_dir, exist_ok=True)

    # Setup paths
    train_path = f"{base_path}/train/"
    valid_path = f"{base_path}/valid/"
    test_path = f"{base_path}/test/"

    train_csv = os.path.join(train_path, "_annotations.csv")
    valid_csv = os.path.join(valid_path, "_annotations.csv")
    test_csv = os.path.join(test_path, "_annotations.csv") if os.path.exists(os.path.join(test_path, "_annotations.csv")) else None

    # Data transformations
    train_transform = T.Compose([
        T.ToTensor(),
        T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])

    valid_transform = T.Compose([
        T.ToTensor(),
        T.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])

    # Create datasets and dataloaders
    train_dataset = LunarDataset(csv_file=train_csv, img_dir=train_path, transform=train_transform)
    valid_dataset = LunarDataset(csv_file=valid_csv, img_dir=valid_path, transform=valid_transform)

    def collate_fn(batch):
        # Filter out any None or invalid entries
        batch = [b for b in batch if b is not None and isinstance(b, tuple) and len(b) == 3]
        if not batch:
            return None
        return tuple(zip(*batch))

    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, collate_fn=collate_fn, num_workers=0)
    valid_loader = DataLoader(valid_dataset, batch_size=batch_size, shuffle=False, collate_fn=collate_fn, num_workers=0)

    # Build model
    model = build_crater_detection_model(num_classes=3, num_slots=num_slots, feature_dim=feature_dim)
    device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
    torch.cuda.empty_cache()
    model.to(device)

    # Optimizer and scheduler
    optimizer = AdamW(model.parameters(), lr=2e-4, weight_decay=0.01)
    scheduler = StepLR(optimizer, step_size=3, gamma=0.1)

    # History dictionary to store all metrics
    history = {
        'epoch': [],
        'train_loss': [],
        'valid_loss': [],
        'train_accuracy': [],
        'valid_accuracy': [],
        'train_precision': [],
        'train_recall': [],
        'train_f1': [],
        'valid_precision': [],
        'valid_recall': [],
        'valid_f1': []
    }

    # Start timing for training
    start_time = time.time()

    # Training and validation loop
    for epoch in range(num_epochs):
        model.train()
        train_loss = 0.0
        train_preds, train_labels = [], []
        batch_count = 0

        for batch in train_loader:
            if batch is None:
                print("Skipping invalid batch")
                continue

            images, targets, _ = batch
            # Ensure all images and targets are valid
            valid_batch = True
            for img, tgt in zip(images, targets):
                if img is None or tgt is None or 'boxes' not in tgt or 'labels' not in tgt:
                    valid_batch = False
                    break
            if not valid_batch:
                print("Skipping batch due to invalid images or targets")
                continue

            images = list(image.to(device) for image in images)
            targets = [{k: v.to(device) for k, v in t.items()} for t in targets]

            try:
                loss_dict = model(images, targets)
                losses = sum(loss for loss in loss_dict.values())
            except Exception as e:
                print(f"Error during loss computation: {e}")
                continue

            if not torch.isfinite(losses):
                print("Loss is not finite. Skipping batch.")
                continue

            losses.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()
            optimizer.zero_grad()

            train_loss += losses.item()
            batch_count += 1

            # Collect predictions for metrics
            with torch.no_grad():
                model.eval()  # Switch to eval mode for inference
                outputs = model(images)
                model.train()  # Switch back to train mode
                batch_preds, batch_labels = match_predictions_to_targets(outputs, targets)
                train_preds.extend(batch_preds)
                train_labels.extend(batch_labels)

        # Calculate average training loss for the epoch
        train_loss /= batch_count if batch_count > 0 else 1

        # Calculate training metrics if we have predictions
        if train_preds and train_labels:
            train_accuracy = accuracy_score(train_labels, train_preds)
            train_precision, train_recall, train_f1, _ = precision_recall_fscore_support(
                train_labels, train_preds, average='weighted', zero_division=0)
        else:
            train_accuracy, train_precision, train_recall, train_f1 = 0, 0, 0, 0

        # Validation phase
        model.eval()
        valid_loss = 0.0
        valid_preds, valid_labels = [], []
        valid_batch_count = 0

        with torch.no_grad():
            for batch in valid_loader:
                if batch is None:
                    continue

                images, targets, _ = batch
                valid_batch = True
                for img, tgt in zip(images, targets):
                    if img is None or tgt is None or 'boxes' not in tgt or 'labels' not in tgt:
                        valid_batch = False
                        break
                if not valid_batch:
                    continue

                images = list(image.to(device) for image in images)
                targets = [{k: v.to(device) for k, v in t.items()} for t in targets]

                try:
                    loss_dict = model(images, targets)
                    losses = sum(loss for loss in loss_dict.values())
                except Exception as e:
                    print(f"Error during validation loss computation: {e}")
                    continue

                if torch.isfinite(losses):
                    valid_loss += losses.item()
                    valid_batch_count += 1

                outputs = model(images)
                batch_preds, batch_labels = match_predictions_to_targets(outputs, targets)
                valid_preds.extend(batch_preds)
                valid_labels.extend(batch_labels)

        # Calculate average validation loss
        valid_loss /= valid_batch_count if valid_batch_count > 0 else 1

        # Calculate validation metrics if we have predictions
        if valid_preds and valid_labels:
            valid_accuracy = accuracy_score(valid_labels, valid_preds)
            valid_precision, valid_recall, valid_f1, _ = precision_recall_fscore_support(
                valid_labels, valid_preds, average='weighted', zero_division=0)
        else:
            valid_accuracy, valid_precision, valid_recall, valid_f1 = 0, 0, 0, 0

        # Step the learning rate scheduler
        scheduler.step()

        # Print epoch summary
        print(f"Epoch {epoch+1}/{num_epochs} | "
              f"Train Loss: {train_loss:.5f}, Valid Loss: {valid_loss:.5f} | "
              f"Train Acc: {train_accuracy:.4f}, Valid Acc: {valid_accuracy:.4f} | "
              f"Train F1: {train_f1:.4f}, Valid F1: {valid_f1:.4f}")

        # Store metrics in history
        history['epoch'].append(epoch+1)
        history['train_loss'].append(train_loss)
        history['valid_loss'].append(valid_loss)
        history['train_accuracy'].append(train_accuracy)
        history['valid_accuracy'].append(valid_accuracy)
        history['train_precision'].append(train_precision)
        history['train_recall'].append(train_recall)
        history['train_f1'].append(train_f1)
        history['valid_precision'].append(valid_precision)
        history['valid_recall'].append(valid_recall)
        history['valid_f1'].append(valid_f1)

        # Save checkpoint
        checkpoint_path = os.path.join(output_dir, f'checkpoint_epoch_{epoch+1}.pth')
        torch.save({
            'epoch': epoch,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'scheduler_state_dict': scheduler.state_dict(),
            'train_loss': train_loss,
            'valid_loss': valid_loss,
        }, checkpoint_path)

        # Save best model based on validation F1 score
        if epoch == 0 or valid_f1 > max(history['valid_f1'][:-1]):
            best_model_path = os.path.join(output_dir, 'best_model.pth')
            torch.save(model.state_dict(), best_model_path)
            print(f"Saved best model at epoch {epoch+1} with validation F1: {valid_f1:.4f}")

    # Calculate total training time
    total_time = time.time() - start_time
    hours, rem = divmod(total_time, 3600)
    minutes, seconds = divmod(rem, 60)
    print(f"Total training time: {int(hours)}h {int(minutes)}m {seconds:.2f}s")

    # Plot metrics
    plot_metrics(history, output_dir)

    # Test evaluation if a test set is available
    if test_csv and os.path.exists(test_csv):
        test_dataset = LunarDataset(csv_file=test_csv, img_dir=test_path, transform=valid_transform)
        test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, collate_fn=collate_fn)

        # Load best model for testing
        model.load_state_dict(torch.load(os.path.join(output_dir, 'best_model.pth')))
        model.eval()

        # Run test evaluation
        test_preds, test_labels = [], []

        with torch.no_grad():
            for batch in test_loader:
                if batch is None:
                    continue

                images, targets, _ = batch
                valid_batch = True
                for img, tgt in zip(images, targets):
                    if img is None or tgt is None or 'boxes' not in tgt or 'labels' not in tgt:
                        valid_batch = False
                        break
                if not valid_batch:
                    continue

                images = list(image.to(device) for image in images)
                targets = [{k: v.to(device) for k, v in t.items()} for t in targets]

                outputs = model(images)
                batch_preds, batch_labels = match_predictions_to_targets(outputs, targets)
                test_preds.extend(batch_preds)
                test_labels.extend(batch_labels)

        # Calculate test metrics
        test_accuracy = accuracy_score(test_labels, test_preds) if test_preds else 0
        test_precision, test_recall, test_f1, _ = precision_recall_fscore_support(
            test_labels, test_preds, average='weighted', zero_division=0) if test_preds else (0, 0, 0, None)

        # Print test results
        print("\nTest Results:")
        print(f"Accuracy: {test_accuracy:.4f}")
        print(f"Precision: {test_precision:.4f}")
        print(f"Recall: {test_recall:.4f}")
        print(f"F1 Score: {test_f1:.4f}")

        # Plot confusion matrix
        if test_preds:
            class_names = train_dataset.classes
            plot_confusion_matrix(test_labels, test_preds, class_names, output_dir)

        # Visualize model predictions on test set
        visualize_predictions(
            model=model,
            data_loader=test_loader,
            class_names=train_dataset.classes,
            device=device,
            score_threshold=0.5,
            max_images=10,
            save_dir=output_dir
        )

    print(f"Training and evaluation completed. Results saved to {output_dir}")
    return model, history

def main():
    base_path = "/content/drive/MyDrive/final_dataset"  # Replace with actual dataset path
    output_dir = "/content/drive/MyDrive/EfficientNet"  # Replace with desired output directory

    # Train and evaluate the model
    model, history = train_and_evaluate(
        base_path=base_path,
        output_dir=output_dir,
        num_epochs=20,
        batch_size=32,  # Reduced batch size to avoid memory issues
        num_slots=10,
        feature_dim=256
    )

if __name__ == "__main__":
    main()