# -*- coding: utf-8 -*-
"""fastercnn2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SCzWQ3S-JSY5u2X9FF9dSMO-Qs1G_Ptz
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import pandas as pd
import numpy as np
import torch
import torchvision
from PIL import Image
from torch.utils.data import Dataset, DataLoader
from torchvision.models.detection import fasterrcnn_resnet50_fpn
from torchvision.transforms import functional as F
from torchvision.ops import box_iou
import matplotlib.pyplot as plt
from sklearn.metrics import precision_recall_fscore_support, accuracy_score
from tqdm import tqdm
import itertools # Import the itertools module

class CraterBoulderDataset(Dataset):
    def __init__(self, annotations, img_dir, transforms=None):
        self.img_dir = img_dir
        self.transforms = transforms
        self.annotations = annotations
        self.image_files = list(self.annotations['filename'].unique())

    def __getitem__(self, idx):
        img_name = self.image_files[idx]
        img_path = os.path.join(self.img_dir, img_name)
        img = Image.open(img_path).convert("RGB")

        records = self.annotations[self.annotations['filename'] == img_name]
        boxes = records[['xmin', 'ymin', 'xmax', 'ymax']].values
        boxes = torch.as_tensor(boxes, dtype=torch.float32)

        labels = records['class'].astype('category').cat.codes + 1  # start labels from 1
        labels = torch.as_tensor(labels.values, dtype=torch.int64)

        target = {
            'boxes': boxes,
            'labels': labels,
            'image_id': torch.tensor([idx])
        }

        if self.transforms:
            img = self.transforms(img)

        return img, target

    def __len__(self):
        return len(self.image_files)

def collate_fn(batch):
    return tuple(zip(*batch))

def get_transform():
    return F.to_tensor

# Modified train_model function to track both training and test loss
def train_model(model, train_loader, test_loader, optimizer, num_epochs=25, device='cuda'):
    """
    Train the model and track both training and testing metrics
    """
    import time
    start_time = time.time()

    # Track metrics
    train_losses = []
    test_losses = []
    train_accuracies = []
    test_accuracies = []

    print("Starting training...")

    for epoch in range(num_epochs):
        # Training phase
        model.train()
        epoch_loss = 0.0
        batch_count = 0

        print(f"Epoch {epoch+1}/{num_epochs}")
        progress_bar = tqdm(train_loader, desc="Training")

        for images, targets in progress_bar:
            images = list(img.to(device) for img in images)
            targets = [{k: v.to(device) for k, v in t.items()} for t in targets]

            # Forward pass
            loss_dict = model(images, targets)
            losses = sum(loss for loss in loss_dict.values())

            # Backward pass
            optimizer.zero_grad()
            losses.backward()
            optimizer.step()

            # Track metrics
            epoch_loss += losses.item()
            batch_count += 1
            progress_bar.set_postfix(loss=losses.item())

        avg_epoch_loss = epoch_loss / batch_count if batch_count > 0 else 0
        train_losses.append(avg_epoch_loss)

        # Testing phase - calculate loss
        model.eval()
        test_epoch_loss = 0.0
        test_batch_count = 0

        print("Evaluating test loss...")
        with torch.no_grad():
            for images, targets in tqdm(list(itertools.islice(test_loader, min(50, len(test_loader)))), desc="Testing"):
                images = list(img.to(device) for img in images)
                targets = [{k: v.to(device) for k, v in t.items()} for t in targets]

                # Forward pass in eval mode (need to handle differently since model doesn't return loss in eval mode)
                # We'll manually compute the loss
                model.train()  # Temporarily set to train mode to get losses
                loss_dict = model(images, targets)
                test_loss = sum(loss for loss in loss_dict.values())
                model.eval()  # Set back to eval mode

                test_epoch_loss += test_loss.item()
                test_batch_count += 1

        avg_test_loss = test_epoch_loss / test_batch_count if test_batch_count > 0 else 0
        test_losses.append(avg_test_loss)

        # Calculate training accuracy (on a sample for speed)
        print("Evaluating training accuracy...")
        train_metrics = evaluate_model(model, train_loader, device, sample_size=min(20, len(train_loader)))
        train_accuracies.append(train_metrics['accuracy'])

        # Calculate test accuracy
        print("Evaluating test accuracy...")
        test_metrics = evaluate_model(model, test_loader, device, sample_size=min(50, len(test_loader)))
        test_accuracies.append(test_metrics['accuracy'])

        print(f"Epoch {epoch+1}/{num_epochs} - "
              f"Train Loss: {avg_epoch_loss:.4f}, Test Loss: {avg_test_loss:.4f}, "
              f"Train Accuracy: {train_metrics['accuracy']:.4f}, "
              f"Test Accuracy: {test_metrics['accuracy']:.4f}")

        # Save model checkpoint every 5 epochs
        if (epoch + 1) % 5 == 0:
            torch.save(model.state_dict(), f"/content/drive/MyDrive/models/faster_rcnn_epoch_{epoch+1}.pth")

    end_time = time.time()
    execution_time = end_time - start_time
    print(f"Total training time: {execution_time:.2f} seconds ({execution_time/60:.2f} minutes)")

    # Save metrics to CSV
    metrics_df = pd.DataFrame({
        'epoch': list(range(1, num_epochs + 1)),
        'train_loss': train_losses,
        'test_loss': test_losses,
        'train_accuracy': train_accuracies,
        'test_accuracy': test_accuracies,
        'execution_time': execution_time
    })
    metrics_df.to_csv('/content/drive/MyDrive/Required/fastercnn/model_history.csv', index=False)
    print("Model history saved to model_history.csv")

    # Plot training and test metrics
    plt.figure(figsize=(12, 15))

    # Plot training vs test loss
    plt.subplot(3, 1, 1)
    plt.plot(range(1, num_epochs + 1), train_losses, 'b-', label='Training Loss')
    plt.plot(range(1, num_epochs + 1), test_losses, 'r-', label='Testing Loss')
    plt.title('Training vs Testing Loss')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True)

    # Plot training vs test accuracy
    plt.subplot(3, 1, 2)
    plt.plot(range(1, num_epochs + 1), train_accuracies, 'b-', label='Training Accuracy')
    plt.plot(range(1, num_epochs + 1), test_accuracies, 'r-', label='Testing Accuracy')
    plt.title('Training vs Testing Accuracy')
    plt.xlabel('Epoch')
    plt.ylabel('Accuracy')
    plt.legend()
    plt.grid(True)

    # Plot loss vs accuracy
    plt.subplot(3, 1, 3)
    plt.plot(train_losses, train_accuracies, 'bo-', label='Training')
    plt.plot(test_losses, test_accuracies, 'ro-', label='Testing')
    plt.title('Loss vs Accuracy')
    plt.xlabel('Loss')
    plt.ylabel('Accuracy')
    plt.legend()
    plt.grid(True)

    plt.tight_layout()
    plt.savefig('/content/drive/MyDrive/Required/fastercnn/training_metrics.png')
    plt.show()

    return model, {
        'train_losses': train_losses,
        'test_losses': test_losses,
        'train_accuracies': train_accuracies,
        'test_accuracies': test_accuracies,
        'execution_time': execution_time
    }

def visualize_detection(model, test_loader, device, label_map, num_images=5, conf_threshold=0.5):
    """
    Visualize crater and boulder detections on test images
    """
    model.eval()

    # Color map for different classes
    colors = {
        1: (0, 255, 0),  # Green for first class
        2: (255, 0, 0)   # Red for second class
    }

    # Get a batch of images
    images, targets = next(iter(test_loader))

    plt.figure(figsize=(15, 15))

    for i in range(min(num_images, len(images))):
        # Get the image
        image = images[i].to(device)
        target = targets[i]

        # Get predictions
        with torch.no_grad():
            prediction = model([image])[0]

        # Convert image for display
        image_np = image.cpu().permute(1, 2, 0).numpy()

        # Normalize image for display
        image_np = (image_np - image_np.min()) / (image_np.max() - image_np.min())

        # Create a copy for drawing
        image_display = image_np.copy()

        plt.subplot(num_images, 2, i*2 + 1)
        plt.title('Ground Truth')
        plt.imshow(image_np)

        # Draw ground truth boxes
        for box, label in zip(target['boxes'], target['labels']):
            x1, y1, x2, y2 = box.numpy()
            class_id = label.item()
            class_name = label_map.get(class_id, f"Class {class_id}")
            color = colors.get(class_id, (0, 0, 255))  # Default blue

            # Convert color to matplotlib format (0-1)
            color_norm = [c/255 for c in color]

            # Create rectangle patch
            rect = plt.Rectangle((x1, y1), x2-x1, y2-y1, linewidth=2,
                                edgecolor=color_norm, facecolor='none')
            plt.gca().add_patch(rect)
            plt.text(x1, y1, class_name, fontsize=10,
                    bbox=dict(facecolor=color_norm, alpha=0.5))

        plt.subplot(num_images, 2, i*2 + 2)
        plt.title('Predictions')
        plt.imshow(image_np)

        # Apply confidence threshold
        keep = prediction['scores'] >= conf_threshold
        boxes = prediction['boxes'][keep].cpu().numpy()
        labels = prediction['labels'][keep].cpu().numpy()
        scores = prediction['scores'][keep].cpu().numpy()

        # Draw predicted boxes
        for box, label, score in zip(boxes, labels, scores):
            x1, y1, x2, y2 = box
            class_id = label
            class_name = label_map.get(class_id, f"Class {class_id}")
            color = colors.get(class_id, (0, 0, 255))  # Default blue

            # Convert color to matplotlib format (0-1)
            color_norm = [c/255 for c in color]

            # Create rectangle patch
            rect = plt.Rectangle((x1, y1), x2-x1, y2-y1, linewidth=2,
                                edgecolor=color_norm, facecolor='none')
            plt.gca().add_patch(rect)
            plt.text(x1, y1, f"{class_name}: {score:.2f}", fontsize=10,
                    bbox=dict(facecolor=color_norm, alpha=0.5))

    plt.tight_layout()
    plt.savefig('/content/drive/MyDrive/Required/fastercnn/detection_visualization.png')
    plt.show()

    return True

def evaluate_model(model, test_loader, device, iou_threshold=0.5, conf_threshold=0.5, sample_size=None):
    """
    Evaluate the model on test data
    sample_size: if provided, only evaluate on this many batches (for quick training accuracy estimation)
    """
    model.eval()

    all_metrics = {
        'true_positives': 0,
        'false_positives': 0,
        'false_negatives': 0,
        'per_class': {}
    }

    # Use only a subset of data if sample_size is specified
    if sample_size is not None:
        data_iterator = list(itertools.islice(test_loader, sample_size))
        print(f"Evaluating on {len(data_iterator)} batches...")
    else:
        data_iterator = test_loader
        print("Evaluating on full dataset...")

    for images, targets in tqdm(data_iterator):
        images = list(img.to(device) for img in images)
        targets = [{k: v.to('cpu') for k, v in t.items()} for t in targets]

        # Get predictions
        with torch.no_grad():
            predictions = model(images)

        # Process each prediction
        for pred, target in zip(predictions, targets):
            # Apply confidence threshold
            keep = pred['scores'] >= conf_threshold
            pred_boxes = pred['boxes'][keep].cpu()
            pred_labels = pred['labels'][keep].cpu()

            true_boxes = target['boxes']
            true_labels = target['labels']

            # Skip if no boxes to compare
            if len(pred_boxes) == 0 and len(true_boxes) == 0:
                continue

            # All predictions are false positives if no true boxes
            if len(true_boxes) == 0:
                all_metrics['false_positives'] += len(pred_boxes)

                # Track per-class metrics
                for pred_label in pred_labels:
                    label_id = pred_label.item()
                    if label_id not in all_metrics['per_class']:
                        all_metrics['per_class'][label_id] = {'TP': 0, 'FP': 0, 'FN': 0}
                    all_metrics['per_class'][label_id]['FP'] += 1

                continue

            # All true boxes are false negatives if no predictions
            if len(pred_boxes) == 0:
                all_metrics['false_negatives'] += len(true_boxes)

                # Track per-class metrics
                for true_label in true_labels:
                    label_id = true_label.item()
                    if label_id not in all_metrics['per_class']:
                        all_metrics['per_class'][label_id] = {'TP': 0, 'FP': 0, 'FN': 0}
                    all_metrics['per_class'][label_id]['FN'] += 1

                continue

            # Calculate IoU between predictions and ground truth
            ious = box_iou(pred_boxes, true_boxes)

            # Track which ground truths have been matched
            gt_matched = torch.zeros(len(true_boxes))

            # For each prediction, find the best match
            for pred_idx in range(len(pred_boxes)):
                pred_label = pred_labels[pred_idx].item()

                # Initialize per-class metrics if needed
                if pred_label not in all_metrics['per_class']:
                    all_metrics['per_class'][pred_label] = {'TP': 0, 'FP': 0, 'FN': 0}

                # Find best matching ground truth
                best_iou, best_gt_idx = torch.max(ious[pred_idx], dim=0)

                if best_iou >= iou_threshold and gt_matched[best_gt_idx] == 0:
                    # Check if labels match
                    if pred_label == true_labels[best_gt_idx].item():
                        # True positive
                        all_metrics['true_positives'] += 1
                        all_metrics['per_class'][pred_label]['TP'] += 1
                        gt_matched[best_gt_idx] = 1
                    else:
                        # False positive (wrong class)
                        all_metrics['false_positives'] += 1
                        all_metrics['per_class'][pred_label]['FP'] += 1
                else:
                    # False positive (no match or already matched)
                    all_metrics['false_positives'] += 1
                    all_metrics['per_class'][pred_label]['FP'] += 1

            # Find unmatched ground truths (false negatives)
            for gt_idx in range(len(true_boxes)):
                if gt_matched[gt_idx] == 0:
                    gt_label = true_labels[gt_idx].item()

                    # Initialize per-class metrics if needed
                    if gt_label not in all_metrics['per_class']:
                        all_metrics['per_class'][gt_label] = {'TP': 0, 'FP': 0, 'FN': 0}

                    all_metrics['false_negatives'] += 1
                    all_metrics['per_class'][gt_label]['FN'] += 1

    # Calculate overall metrics
    tp = all_metrics['true_positives']
    fp = all_metrics['false_positives']
    fn = all_metrics['false_negatives']

    precision = tp / (tp + fp) if (tp + fp) > 0 else 0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0
    accuracy = tp / (tp + fp + fn) if (tp + fp + fn) > 0 else 0

    # Calculate per-class metrics
    per_class_metrics = {}
    for cls_id, metrics in all_metrics['per_class'].items():
        cls_tp = metrics['TP']
        cls_fp = metrics['FP']
        cls_fn = metrics['FN']

        cls_precision = cls_tp / (cls_tp + cls_fp) if (cls_tp + cls_fp) > 0 else 0
        cls_recall = cls_tp / (cls_tp + cls_fn) if (cls_tp + cls_fn) > 0 else 0
        cls_f1 = 2 * cls_precision * cls_recall / (cls_precision + cls_recall) if (cls_precision + cls_recall) > 0 else 0

        per_class_metrics[cls_id] = {
            'precision': cls_precision,
            'recall': cls_recall,
            'f1': cls_f1,
            'TP': cls_tp,
            'FP': cls_fp,
            'FN': cls_fn
        }

    # Return all metrics
    return {
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1': f1,
        'per_class': per_class_metrics,
        'raw_counts': {
            'TP': tp,
            'FP': fp,
            'FN': fn
        }
    }

def plot_metrics(metrics, label_map):
    """
    Plot various metrics as bar charts
    """
    # Plot overall metrics
    fig, ax = plt.subplots(figsize=(8, 5))
    metrics_to_plot = ['accuracy', 'precision', 'recall', 'f1']
    values = [metrics[m] for m in metrics_to_plot]

    ax.bar(metrics_to_plot, values, color=['blue', 'green', 'orange', 'red'])
    ax.set_ylim(0, 1)
    ax.set_title('Overall Detection Metrics')
    ax.set_ylabel('Score')

    # Add values on bars
    for i, v in enumerate(values):
        ax.text(i, v + 0.01, f'{v:.3f}', ha='center')

    plt.tight_layout()
    plt.savefig('/content/drive/MyDrive/Required/fastercnn/overall_metrics.png')
    plt.show()

    # Plot per-class metrics
    if len(metrics['per_class']) > 0:
        # Get class names
        class_names = [label_map.get(cls_id, f"Class {cls_id}") for cls_id in metrics['per_class'].keys()]
        class_precision = [metrics['per_class'][cls_id]['precision'] for cls_id in metrics['per_class'].keys()]
        class_recall = [metrics['per_class'][cls_id]['recall'] for cls_id in metrics['per_class'].keys()]
        class_f1 = [metrics['per_class'][cls_id]['f1'] for cls_id in metrics['per_class'].keys()]

        # Create grouped bar chart
        fig, ax = plt.subplots(figsize=(10, 6))
        x = np.arange(len(class_names))
        width = 0.25

        ax.bar(x - width, class_precision, width, label='Precision', color='green')
        ax.bar(x, class_recall, width, label='Recall', color='orange')
        ax.bar(x + width, class_f1, width, label='F1', color='red')

        ax.set_ylabel('Score')
        ax.set_title('Per-Class Metrics')
        ax.set_xticks(x)
        ax.set_xticklabels(class_names)
        ax.legend()

        plt.tight_layout()
        plt.savefig('/content/drive/MyDrive/Required/fastercnn/per_class_metrics.png')
        plt.show()

def plot_precision_recall_curve(model, test_loader, device, label_map):
    """
    Plot precision-recall curve at different confidence thresholds
    """
    thresholds = np.arange(0.1, 1.0, 0.1)
    precisions = []
    recalls = []
    f1_scores = []

    print("Calculating precision-recall curve...")
    for threshold in tqdm(thresholds):
        metrics = evaluate_model(model, test_loader, device, conf_threshold=threshold)
        precisions.append(metrics['precision'])
        recalls.append(metrics['recall'])
        f1_scores.append(metrics['f1'])

    # Plot precision-recall curve
    plt.figure(figsize=(10, 6))
    plt.plot(recalls, precisions, 'bo-', linewidth=2, markersize=8)

    # Add threshold labels
    for i, thresh in enumerate(thresholds):
        plt.annotate(f'{thresh:.1f}', (recalls[i], precisions[i]),
                    textcoords="offset points", xytext=(0, 10), ha='center')

    plt.xlabel('Recall')
    plt.ylabel('Precision')
    plt.title('Precision-Recall Curve')
    plt.grid(True)
    plt.savefig('/content/drive/MyDrive/Required/fastercnn/precision_recall_curve.png')
    plt.show()

    # Plot F1 score vs threshold
    plt.figure(figsize=(10, 6))
    plt.plot(thresholds, f1_scores, 'ro-', linewidth=2, markersize=8)
    plt.xlabel('Confidence Threshold')
    plt.ylabel('F1 Score')
    plt.title('F1 Score vs Confidence Threshold')
    plt.grid(True)
    plt.savefig('/content/drive/MyDrive/Required/fastercnn/f1_threshold.png')
    plt.show()

    # Print optimal threshold
    best_f1_idx = np.argmax(f1_scores)
    print(f"Optimal threshold: {thresholds[best_f1_idx]:.1f} (F1 = {f1_scores[best_f1_idx]:.4f})")

    # Create table of values
    results_df = pd.DataFrame({
        'Threshold': thresholds,
        'Precision': precisions,
        'Recall': recalls,
        'F1': f1_scores
    })

    print("\nPrecision-Recall values:")
    print(results_df)

    return results_df

def plot_confusion_matrix(model, test_loader, device, label_map, conf_threshold=0.5):
    """
    Plot confusion matrix for the model
    """
    model.eval()

    # Initialize confusion matrix
    num_classes = len(label_map) + 1  # +1 for background
    confusion_matrix = np.zeros((num_classes, num_classes), dtype=int)

    print("Calculating confusion matrix...")
    for images, targets in tqdm(test_loader):
        images = list(img.to(device) for img in images)
        targets = [{k: v.to('cpu') for k, v in t.items()} for t in targets]

        # Get predictions
        with torch.no_grad():
            predictions = model(images)

        # Process each prediction
        for pred, target in zip(predictions, targets):
            # Apply confidence threshold
            keep = pred['scores'] >= conf_threshold
            pred_boxes = pred['boxes'][keep].cpu()
            pred_labels = pred['labels'][keep].cpu()

            true_boxes = target['boxes']
            true_labels = target['labels']

            # Skip if no boxes to compare
            if len(pred_boxes) == 0 or len(true_boxes) == 0:
                continue

            # Calculate IoU between predictions and ground truth
            ious = box_iou(pred_boxes, true_boxes)

            # For each prediction, find the best match
            for pred_idx in range(len(pred_boxes)):
                pred_label = pred_labels[pred_idx].item()

                if len(true_boxes) > 0:
                    best_iou, best_gt_idx = torch.max(ious[pred_idx], dim=0)

                    if best_iou >= 0.5:
                        true_label = true_labels[best_gt_idx].item()
                        confusion_matrix[true_label, pred_label] += 1

    # Plot the confusion matrix
    plt.figure(figsize=(10, 8))
    plt.imshow(confusion_matrix[1:, 1:], interpolation='nearest', cmap=plt.cm.Blues)  # Skip background class
    plt.title('Confusion Matrix')

    # Add labels
    class_names = [label_map.get(i, f'Class {i}') for i in range(1, num_classes)]
    tick_marks = np.arange(len(class_names))
    plt.xticks(tick_marks, class_names, rotation=45)
    plt.yticks(tick_marks, class_names)

    # Add text annotations
    thresh = confusion_matrix[1:, 1:].max() / 2.
    for i in range(len(class_names)):
        for j in range(len(class_names)):
            plt.text(j, i, format(confusion_matrix[i+1, j+1], 'd'),
                    ha="center", va="center",
                    color="white" if confusion_matrix[i+1, j+1] > thresh else "black")

    plt.ylabel('True label')
    plt.xlabel('Predicted label')
    plt.tight_layout()
    plt.savefig('/content/drive/MyDrive/Required/fastercnn/confusion_matrix.png')
    plt.show()

def main():
    # Set random seed for reproducibility
    torch.manual_seed(42)
    np.random.seed(42)

    # Set device
    device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
    print(f"Using device: {device}")

    # Paths
    train_folder = '/content/drive/MyDrive/final_dataset/train'
    test_folder = '/content/drive/MyDrive/final_dataset/test'
    train_annotations_path = os.path.join(train_folder, '_annotations.csv')
    test_annotations_path = os.path.join(test_folder, '_annotations.csv')

    # Load annotations
    train_annotations = pd.read_csv(train_annotations_path)
    test_annotations = pd.read_csv(test_annotations_path)

    # Create label map
    label_map = {i+1: cls for i, cls in enumerate(train_annotations['class'].astype('category').cat.categories)}
    print(f"Label map: {label_map}")

    # Create datasets
    train_dataset = CraterBoulderDataset(train_annotations, train_folder, transforms=get_transform())
    test_dataset = CraterBoulderDataset(test_annotations, test_folder, transforms=get_transform())

    # Create data loaders
    train_loader = DataLoader(train_dataset, batch_size=4, shuffle=True, collate_fn=collate_fn)
    test_loader = DataLoader(test_dataset, batch_size=4, shuffle=False, collate_fn=collate_fn)

    # Model parameters
    num_classes = len(label_map) + 1  # +1 for background

    # Create or load model
    option = input("Enter 1 to train a new model or 2 to load an existing model: ")

    if option == '1':
        # Create model
        print("Creating new model...")
        model = fasterrcnn_resnet50_fpn(weights='DEFAULT')
        in_features = model.roi_heads.box_predictor.cls_score.in_features
        model.roi_heads.box_predictor = torchvision.models.detection.faster_rcnn.FastRCNNPredictor(in_features, num_classes)
        model.to(device)

        # Train model
        optimizer = torch.optim.SGD(model.parameters(), lr=0.005, momentum=0.9, weight_decay=0.0005)
        num_epochs = int(input("Enter number of epochs to train: "))
        model, train_history = train_model(model, train_loader, test_loader, optimizer, num_epochs=num_epochs, device=device)

        # Save model
        torch.save(model.state_dict(), "/content/drive/MyDrive/models/faster_rcnn_final.pth")
        print("Model saved as 'faster_rcnn_final.pth'")

    elif option == '2':
        # Load model
        model_path = input("Enter path to model file: ")
        print(f"Loading model from {model_path}...")

        model = fasterrcnn_resnet50_fpn(weights=None)
        in_features = model.roi_heads.box_predictor.cls_score.in_features
        model.roi_heads.box_predictor = torchvision.models.detection.faster_rcnn.FastRCNNPredictor(in_features, num_classes)
        model.load_state_dict(torch.load(model_path, map_location=device))
        model.to(device)

    else:
        print("Invalid option. Exiting.")
        return

    # Evaluate model
    print("\nEvaluating model...")
    metrics = evaluate_model(model, test_loader, device)

    # Print metrics
    print("\n📊 Model Evaluation Results:")
    print(f"Accuracy: {metrics['accuracy']:.4f}")
    print(f"Precision: {metrics['precision']:.4f}")
    print(f"Recall: {metrics['recall']:.4f}")
    print(f"F1 Score: {metrics['f1']:.4f}")

    print("\nPer-class metrics:")
    for cls_id, cls_metrics in metrics['per_class'].items():
        cls_name = label_map.get(cls_id, f"Class {cls_id}")
        print(f"  {cls_name}:")
        print(f"    Precision: {cls_metrics['precision']:.4f}")
        print(f"    Recall: {cls_metrics['recall']:.4f}")
        print(f"    F1 Score: {cls_metrics['f1']:.4f}")
        print(f"    TP: {cls_metrics['TP']}, FP: {cls_metrics['FP']}, FN: {cls_metrics['FN']}")

    # Plot metrics
    plot_metrics(metrics, label_map)

    # Visualize detections on test images
    print("\nVisualizing detections on test images...")
    visualize_detection(model, test_loader, device, label_map, num_images=3)

    # Plot precision-recall curve
    print("\nPlotting precision-recall curve...")
    plot_precision_recall_curve(model, test_loader, device, label_map)

    # Plot confusion matrix
    print("\nPlotting confusion matrix...")
    plot_confusion_matrix(model, test_loader, device, label_map)

if __name__ == "__main__":
    main()