# -*- coding: utf-8 -*-
"""imagenet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kOeH6o710RqFo_sWOmPX_0sqYGhrUH9c
"""

import os
import time
import torch
import torchvision
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import precision_recall_fscore_support, roc_auc_score, roc_curve, confusion_matrix
from torch.utils.data import Dataset, DataLoader
from torchvision import models, transforms
import cv2
import albumentations as A
from albumentations.pytorch import ToTensorV2
import torch.nn as nn
import csv
from datetime import datetime

# Set the base path for your dataset
BASE_PATH = "/content/drive/MyDrive/final_dataset"
RESULTS = "/content/drive/MyDrive/Required/imageNet"
RESULTS_PATH = os.path.join(RESULTS, "results")

# Create results directory if it doesn't exist
os.makedirs(RESULTS_PATH, exist_ok=True)

def get_transform(train=True):
    if train:
        return A.Compose([
            A.Resize(224, 224),
            A.HorizontalFlip(p=0.5),
            A.RandomBrightnessContrast(p=0.2),
            A.Normalize(mean=(0.485, 0.456, 0.406),  # ImageNet means
                        std=(0.229, 0.224, 0.225)),
            ToTensorV2()
        ], bbox_params=A.BboxParams(format='pascal_voc', label_fields=['class_labels']))
    else:
        return A.Compose([
            A.Resize(224, 224),
            A.Normalize(mean=(0.485, 0.456, 0.406),
                        std=(0.229, 0.224, 0.225)),
            ToTensorV2()
        ], bbox_params=A.BboxParams(format='pascal_voc', label_fields=['class_labels']))

class CraterBoulderDataset(Dataset):
    def __init__(self, folder_path, transform=None):
        self.folder_path = folder_path
        self.data = pd.read_csv(os.path.join(folder_path, "_annotations.csv"))
        self.transform = transform
        # Filter for images that have at least one 'Crater' or 'Boulder' annotation
        self.image_files = self.data[self.data['class'].isin(['Crater', 'Boulder'])]['filename'].unique()

    def __len__(self):
        return len(self.image_files)

    def __getitem__(self, idx):
        filename = self.image_files[idx]
        img_path = os.path.join(self.folder_path, filename)

        image = cv2.imread(img_path)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        # Get all records for the current image
        records = self.data[self.data['filename'] == filename]

        # Filter records for 'Crater' and 'Boulder' for boxes and labels
        crater_boulder_records = records[records['class'].isin(['Crater', 'Boulder'])]

        # Check if any 'Crater' or 'Boulder' boxes are found for this image
        if len(crater_boulder_records) == 0:
            # If no boxes, return an empty tensor for boxes and labels
            boxes = np.empty((0, 4), dtype=np.float32)
            labels = np.empty((0,), dtype=np.int64)
        else:
            boxes = crater_boulder_records[['xmin', 'ymin', 'xmax', 'ymax']].values
            # Map 'Crater' to 0 and 'Boulder' to 1
            labels = crater_boulder_records['class'].map({'Crater': 0, 'Boulder': 1}).values

        if self.transform:
            transformed = self.transform(image=image, bboxes=boxes, class_labels=labels)
            image = transformed['image']
            boxes = transformed['bboxes']
            labels = transformed['class_labels']

        target = {
            'boxes': torch.tensor(boxes, dtype=torch.float32) if len(boxes) > 0 else torch.zeros((0, 4), dtype=torch.float32),
            'labels': torch.tensor(labels, dtype=torch.long) if len(labels) > 0 else torch.zeros((0,), dtype=torch.long)
        }

        return image, target, filename  # Added filename for visualization purposes

class DetectionModel(nn.Module):
    def __init__(self, num_classes=2):
        super(DetectionModel, self).__init__()
        resnet = models.resnet50(weights='IMAGENET1K_V1')
        self.backbone = nn.Sequential(*list(resnet.children())[:-2])
        self.pool = nn.AdaptiveAvgPool2d((1, 1))
        self.classifier = nn.Linear(2048, num_classes)
        self.bbox_regressor = nn.Linear(2048, 4)

    def forward(self, x):
        x = self.backbone(x)
        x = self.pool(x)
        x = x.view(x.size(0), -1)
        class_logits = self.classifier(x)
        bbox_coords = self.bbox_regressor(x)
        return class_logits, bbox_coords

def collate_fn(batch):
    images = []
    targets = []
    filenames = []
    for img, target, filename in batch:
        images.append(img)
        targets.append(target)
        filenames.append(filename)
    return images, targets, filenames

def train_model(model, dataloader, optimizer, criterion_cls, criterion_bbox, device, epoch, history):
    model.train()
    total_loss = 0
    cls_loss_total = 0
    bbox_loss_total = 0
    correct, total = 0, 0

    all_preds = []
    all_labels = []

    epoch_start = time.time()

    for images, targets, _ in dataloader:
        optimizer.zero_grad()

        batch_loss = 0
        batch_cls_loss = 0
        batch_bbox_loss = 0
        batch_correct = 0

        for i in range(len(images)):
            image = images[i].unsqueeze(0).to(device)
            target = targets[i]

            # Skip images with no annotations
            if len(target['labels']) == 0:
                continue

            labels = target['labels'].to(device)
            boxes = target['boxes'].to(device)

            # Use the first object for simplicity
            label = labels[0]
            box = boxes[0]

            class_logits, bbox_preds = model(image)

            loss_cls = criterion_cls(class_logits, label.unsqueeze(0))
            loss_bbox = criterion_bbox(bbox_preds, box.unsqueeze(0))
            loss = loss_cls + loss_bbox
            loss.backward()

            _, pred = torch.max(class_logits, 1)

            all_preds.append(pred.item())
            all_labels.append(label.item())

            batch_correct += (pred == label.unsqueeze(0)).sum().item()
            batch_loss += loss.item()
            batch_cls_loss += loss_cls.item()
            batch_bbox_loss += loss_bbox.item()

        optimizer.step()
        total_loss += batch_loss / len(images)
        cls_loss_total += batch_cls_loss / len(images)
        bbox_loss_total += batch_bbox_loss / len(images)
        correct += batch_correct
        total += len(images)

    epoch_time = time.time() - epoch_start

    # Calculate metrics
    acc = correct / total if total > 0 else 0

    if len(all_preds) > 0 and len(all_labels) > 0:
        all_preds = np.array(all_preds)
        all_labels = np.array(all_labels)
        precision, recall, f1, _ = precision_recall_fscore_support(all_labels, all_preds, average='weighted', zero_division=0)
    else:
        precision, recall, f1 = 0, 0, 0

    # Update history
    history['train_loss'].append(total_loss / len(dataloader))
    history['train_cls_loss'].append(cls_loss_total / len(dataloader))
    history['train_bbox_loss'].append(bbox_loss_total / len(dataloader))
    history['train_accuracy'].append(acc)
    history['train_precision'].append(precision)
    history['train_recall'].append(recall)
    history['train_f1'].append(f1)
    history['epoch_time'].append(epoch_time)

    print(f"Epoch {epoch+1} - Train: Loss={total_loss/len(dataloader):.4f}, Acc={acc:.4f}, Prec={precision:.4f}, Rec={recall:.4f}, F1={f1:.4f}, Time={epoch_time:.2f}s")

    return total_loss / len(dataloader), acc, precision, recall, f1

def validate_model(model, dataloader, criterion_cls, criterion_bbox, device, epoch, history):
    model.eval()
    total_loss = 0
    cls_loss_total = 0
    bbox_loss_total = 0
    correct, total = 0, 0

    all_preds = []
    all_labels = []
    all_scores = []  # For ROC AUC calculation

    with torch.no_grad():
        for images, targets, _ in dataloader:
            batch_loss = 0
            batch_cls_loss = 0
            batch_bbox_loss = 0
            batch_correct = 0

            for i in range(len(images)):
                image = images[i].unsqueeze(0).to(device)
                target = targets[i]

                # Skip images with no annotations
                if len(target['labels']) == 0:
                    continue

                labels = target['labels'].to(device)
                boxes = target['boxes'].to(device)

                # Use the first object for simplicity
                label = labels[0]
                box = boxes[0]

                class_logits, bbox_preds = model(image)

                loss_cls = criterion_cls(class_logits, label.unsqueeze(0))
                loss_bbox = criterion_bbox(bbox_preds, box.unsqueeze(0))
                loss = loss_cls + loss_bbox

                _, pred = torch.max(class_logits, 1)

                # Store for metrics calculation
                all_preds.append(pred.item())
                all_labels.append(label.item())
                all_scores.append(torch.softmax(class_logits, dim=1)[0][1].item())  # Probability of class 1 (Boulder)

                batch_correct += (pred == label.unsqueeze(0)).sum().item()
                batch_loss += loss.item()
                batch_cls_loss += loss_cls.item()
                batch_bbox_loss += loss_bbox.item()

            total_loss += batch_loss / len(images)
            cls_loss_total += batch_cls_loss / len(images)
            bbox_loss_total += batch_bbox_loss / len(images)
            correct += batch_correct
            total += len(images)

    # Calculate metrics
    acc = correct / total if total > 0 else 0

    if len(all_preds) > 0 and len(all_labels) > 0:
        all_preds = np.array(all_preds)
        all_labels = np.array(all_labels)
        all_scores = np.array(all_scores)

        precision, recall, f1, _ = precision_recall_fscore_support(all_labels, all_preds, average='weighted', zero_division=0)

        # Calculate ROC AUC if we have both classes
        if len(np.unique(all_labels)) > 1:
            auc = roc_auc_score(all_labels, all_scores)
        else:
            auc = 0
    else:
        precision, recall, f1, auc = 0, 0, 0, 0

    # Update history
    history['val_loss'].append(total_loss / len(dataloader))
    history['val_cls_loss'].append(cls_loss_total / len(dataloader))
    history['val_bbox_loss'].append(bbox_loss_total / len(dataloader))
    history['val_accuracy'].append(acc)
    history['val_precision'].append(precision)
    history['val_recall'].append(recall)
    history['val_f1'].append(f1)
    history['val_auc'].append(auc)

    print(f"Epoch {epoch+1} - Val: Loss={total_loss/len(dataloader):.4f}, Acc={acc:.4f}, Prec={precision:.4f}, Rec={recall:.4f}, F1={f1:.4f}, AUC={auc:.4f}")

    return total_loss / len(dataloader), acc, precision, recall, f1, auc

def save_history_to_csv(history, filename):
    """Save training history to a CSV file"""
    with open(filename, 'w', newline='') as csvfile:
        writer = csv.writer(csvfile)
        # Write header
        writer.writerow(['epoch'] + list(history.keys()))
        # Write data for each epoch
        for i in range(len(history['train_loss'])):
            row = [i+1] + [history[key][i] for key in history.keys()]
            writer.writerow(row)
    print(f"History saved to {filename}")

def plot_metrics(history, save_path=None):
    """Plot training and validation metrics"""
    # Plot loss
    plt.figure(figsize=(12, 8))
    plt.subplot(2, 2, 1)
    plt.plot(history['train_loss'], label='Train Loss')
    plt.plot(history['val_loss'], label='Val Loss')
    plt.title('Loss over Epochs')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()

    # Plot accuracy
    plt.subplot(2, 2, 2)
    plt.plot(history['train_accuracy'], label='Train Accuracy')
    plt.plot(history['val_accuracy'], label='Val Accuracy')
    plt.title('Accuracy over Epochs')
    plt.xlabel('Epoch')
    plt.ylabel('Accuracy')
    plt.legend()

    # Plot precision and recall
    plt.subplot(2, 2, 3)
    plt.plot(history['train_precision'], label='Train Precision')
    plt.plot(history['val_precision'], label='Val Precision')
    plt.plot(history['train_recall'], label='Train Recall')
    plt.plot(history['val_recall'], label='Val Recall')
    plt.title('Precision and Recall over Epochs')
    plt.xlabel('Epoch')
    plt.ylabel('Score')
    plt.legend()

    # Plot F1 score
    plt.subplot(2, 2, 4)
    plt.plot(history['train_f1'], label='Train F1')
    plt.plot(history['val_f1'], label='Val F1')
    plt.title('F1 Score over Epochs')
    plt.xlabel('Epoch')
    plt.ylabel('F1 Score')
    plt.legend()

    plt.tight_layout()

    if save_path:
        plt.savefig(save_path)

    plt.show()

def visualize_predictions(model, dataset, device, num_samples=5, save_dir=None):
    """Visualize model predictions on sample images"""
    model.eval()

    if save_dir and not os.path.exists(save_dir):
        os.makedirs(save_dir)

    for i in range(min(num_samples, len(dataset))):
        # Load sample
        image, target, filename = dataset[i]

        # Original image for reference
        original_img = image.permute(1, 2, 0).cpu().numpy()
        original_img = np.clip(original_img * 255, 0, 255).astype(np.uint8)

        # Prepare image for model
        image_batch = image.unsqueeze(0).to(device)

        # Forward pass
        with torch.no_grad():
            class_logits, bbox_preds = model(image_batch)

        # Predicted class and box
        pred_prob = torch.softmax(class_logits, dim=1)
        pred_label = class_logits.argmax(1).item()
        pred_score = pred_prob[0, pred_label].item()
        pred_bbox = bbox_preds[0].detach().cpu().numpy()

        # Ground truth
        if len(target['labels']) > 0:
            gt_label = target['labels'][0].item()
            gt_bbox = target['boxes'][0].cpu().numpy()
            has_gt = True
        else:
            has_gt = False

        # Convert image back to numpy (H, W, C)
        img_np = image.permute(1, 2, 0).cpu().numpy()
        img_np = np.clip(img_np * 255, 0, 255).astype(np.uint8)

        # If you want grayscale, convert the RGB to grayscale
        if img_np.shape[2] == 3:  # RGB image
            img_gray = cv2.cvtColor(img_np, cv2.COLOR_RGB2GRAY)
            # For display, convert back to 3-channel but grayscale
            img_display = cv2.cvtColor(img_gray, cv2.COLOR_GRAY2RGB)
        else:
            img_display = img_np

        # Continue with plotting using img_display
        plt.figure(figsize=(12, 6))
        plt.subplot(1, 2, 1)
        plt.imshow(img_display, cmap='gray')  #
        plt.title("Original Image with Ground Truth")

        if has_gt:
            # Draw ground truth box in red
            rect = plt.Rectangle((gt_bbox[0], gt_bbox[1]),
                                gt_bbox[2] - gt_bbox[0],
                                gt_bbox[3] - gt_bbox[1],
                                linewidth=2, edgecolor='r', facecolor='none')
            plt.gca().add_patch(rect)

            # Add GT label
            gt_text = "Crater" if gt_label == 0 else "Boulder"
            plt.text(gt_bbox[0], gt_bbox[1] - 5, f"GT: {gt_text}",
                    color='r', fontsize=10, bbox=dict(facecolor='white', alpha=0.7))

        plt.axis('off')

        # Image with predictions
        plt.subplot(1, 2, 2)
        plt.imshow(img_np)
        plt.title("Prediction")

        # Draw predicted box in green
        rect = plt.Rectangle((pred_bbox[0], pred_bbox[1]),
                            pred_bbox[2] - pred_bbox[0],
                            pred_bbox[3] - pred_bbox[1],
                            linewidth=2, edgecolor='g', facecolor='none')
        plt.gca().add_patch(rect)

        # Add predicted label and score
        pred_text = "Crater" if pred_label == 0 else "Boulder"
        plt.text(pred_bbox[0], pred_bbox[1] - 5,
                f"Pred: {pred_text} ({pred_score:.2f})",
                color='g', fontsize=10, bbox=dict(facecolor='white', alpha=0.7))

        plt.axis('off')

        # Save if directory is provided
        if save_dir:
            plt.savefig(os.path.join(save_dir, f"pred_{i}_{filename}"))

        plt.tight_layout()
        plt.show()

    return

def calculate_confusion_matrix(model, dataloader, device):
    """Calculate and visualize confusion matrix"""
    model.eval()
    all_preds = []
    all_labels = []

    with torch.no_grad():
        for images, targets, _ in dataloader:
            for i in range(len(images)):
                # Skip images with no annotations
                if len(targets[i]['labels']) == 0:
                    continue

                image = images[i].unsqueeze(0).to(device)
                label = targets[i]['labels'][0].item()

                class_logits, _ = model(image)
                pred = class_logits.argmax(1).item()

                all_preds.append(pred)
                all_labels.append(label)

    if len(all_preds) > 0:
        # Generate confusion matrix
        cm = confusion_matrix(all_labels, all_preds)

        # Plot confusion matrix
        plt.figure(figsize=(8, 6))
        plt.imshow(cm, interpolation='nearest', cmap=plt.cm.Blues)
        plt.title('Confusion Matrix')
        plt.colorbar()

        classes = ['Crater', 'Boulder']
        tick_marks = np.arange(len(classes))
        plt.xticks(tick_marks, classes, rotation=45)
        plt.yticks(tick_marks, classes)

        # Add text annotations
        thresh = cm.max() / 2
        for i in range(cm.shape[0]):
            for j in range(cm.shape[1]):
                plt.text(j, i, format(cm[i, j], 'd'),
                        horizontalalignment="center",
                        color="white" if cm[i, j] > thresh else "black")

        plt.ylabel('True label')
        plt.xlabel('Predicted label')
        plt.tight_layout()
        plt.savefig(os.path.join(RESULTS_PATH, 'confusion_matrix.png'))
        plt.show()

        return cm

    return None

def plot_roc_curve(model, dataloader, device):
    """Plot ROC curve for the model"""
    model.eval()
    all_scores = []
    all_labels = []

    with torch.no_grad():
        for images, targets, _ in dataloader:
            for i in range(len(images)):
                # Skip images with no annotations
                if len(targets[i]['labels']) == 0:
                    continue

                image = images[i].unsqueeze(0).to(device)
                label = targets[i]['labels'][0].item()

                class_logits, _ = model(image)
                score = torch.softmax(class_logits, dim=1)[0][1].item()  # Probability of class 1 (Boulder)

                all_scores.append(score)
                all_labels.append(label)

    if len(all_scores) > 0 and len(np.unique(all_labels)) > 1:
        # Calculate ROC curve
        fpr, tpr, _ = roc_curve(all_labels, all_scores)
        roc_auc = roc_auc_score(all_labels, all_scores)

        # Plot ROC curve
        plt.figure(figsize=(8, 6))
        plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (area = {roc_auc:.2f})')
        plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
        plt.xlim([0.0, 1.0])
        plt.ylim([0.0, 1.05])
        plt.xlabel('False Positive Rate')
        plt.ylabel('True Positive Rate')
        plt.title('Receiver Operating Characteristic (ROC) Curve')
        plt.legend(loc="lower right")
        plt.savefig(os.path.join(RESULTS_PATH, 'roc_curve.png'))
        plt.show()

        return roc_auc

    return None

def main():
    # Set random seed for reproducibility
    torch.manual_seed(42)
    np.random.seed(42)

    # Check if CUDA is available
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    # Create datasets
    train_ds = CraterBoulderDataset(os.path.join(BASE_PATH, 'train'), transform=get_transform(train=True))
    valid_ds = CraterBoulderDataset(os.path.join(BASE_PATH, 'valid'), transform=get_transform(train=False))
    test_ds = CraterBoulderDataset(os.path.join(BASE_PATH, 'test'), transform=get_transform(train=False))

    print(f"Train dataset size: {len(train_ds)}")
    print(f"Validation dataset size: {len(valid_ds)}")
    print(f"Test dataset size: {len(test_ds)}")

    # Create data loaders
    train_loader = DataLoader(train_ds, batch_size=4, shuffle=True, collate_fn=collate_fn)
    valid_loader = DataLoader(valid_ds, batch_size=4, shuffle=False, collate_fn=collate_fn)
    test_loader = DataLoader(test_ds, batch_size=4, shuffle=False, collate_fn=collate_fn)

    # Initialize model
    model = DetectionModel(num_classes=2).to(device)

    # Define optimizer and loss functions
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)
    criterion_cls = nn.CrossEntropyLoss()
    criterion_bbox = nn.MSELoss()

    # Initialize history dictionary
    history = {
        'train_loss': [], 'train_cls_loss': [], 'train_bbox_loss': [],
        'train_accuracy': [], 'train_precision': [], 'train_recall': [], 'train_f1': [],
        'val_loss': [], 'val_cls_loss': [], 'val_bbox_loss': [],
        'val_accuracy': [], 'val_precision': [], 'val_recall': [], 'val_f1': [], 'val_auc': [],
        'epoch_time': []
    }

    # Training start time
    total_start_time = time.time()

    # Number of epochs
    num_epochs = 15

    # Training loop
    for epoch in range(num_epochs):
        # Train
        train_loss, train_acc, train_prec, train_rec, train_f1 = train_model(
            model, train_loader, optimizer, criterion_cls, criterion_bbox, device, epoch, history
        )

        # Validate
        val_loss, val_acc, val_prec, val_rec, val_f1, val_auc = validate_model(
            model, valid_loader, criterion_cls, criterion_bbox, device, epoch, history
        )

    # Total training time
    total_time = time.time() - total_start_time
    print(f"Total training time: {total_time:.2f} seconds")

    # Save training history
    save_history_to_csv(history, os.path.join(RESULTS_PATH, 'training_history.csv'))

    # Save execution time to CSV
    with open(os.path.join(RESULTS_PATH, 'execution_time.csv'), 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(['Total Training Time (s)', 'Average Epoch Time (s)'])
        writer.writerow([total_time, sum(history['epoch_time'])/len(history['epoch_time'])])

    # Plot and save metrics
    plot_metrics(history, save_path=os.path.join(RESULTS_PATH, 'training_metrics.png'))

    # Save model
    torch.save({
        'model_state_dict': model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'history': history,
    }, os.path.join(RESULTS_PATH, 'model_checkpoint.pth'))

    # Evaluate on test set
    test_loss, test_acc, test_prec, test_rec, test_f1, test_auc = validate_model(
        model, test_loader, criterion_cls, criterion_bbox, device, num_epochs, history
    )

    # Save test metrics to CSV
    with open(os.path.join(RESULTS_PATH, 'test_metrics.csv'), 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(['Accuracy', 'Precision', 'Recall', 'F1 Score', 'AUC'])
        writer.writerow([test_acc, test_prec, test_rec, test_f1, test_auc])

    # Visualize test predictions
    visualize_dir = os.path.join(RESULTS_PATH, 'visualizations')
    os.makedirs(visualize_dir, exist_ok=True)
    visualize_predictions(model, test_ds, device, num_samples=10, save_dir=visualize_dir)

    # Generate confusion matrix
    calculate_confusion_matrix(model, test_loader, device)

    # Plot ROC curve
    plot_roc_curve(model, test_loader, device)

    print(f"All results saved to {RESULTS_PATH}")

if __name__ == "__main__":
    main()