# -*- coding: utf-8 -*-
"""unet2.0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RAi2-gppUw1LEQndOD7VIbjzw4HjhqSW
"""

from google.colab import drive
drive.mount('/content/drive')

import cv2
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D, concatenate, Conv2DTranspose, Dropout, BatchNormalization
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
import glob
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Define paths for the updated structure
BASE_DIR = "/content/drive/MyDrive/final_dataset/"
MASK_DIR  = "/content/drive/MyDrive/Masks"
TRAIN_DIR = os.path.join(BASE_DIR, "train")
TEST_DIR = os.path.join(BASE_DIR, "test")
TRAIN_MASK_DIR = os.path.join(MASK_DIR, "train_masks")
TEST_MASK_DIR = os.path.join(MASK_DIR, "test_masks")

# Create mask directories if they don't exist
os.makedirs(TRAIN_MASK_DIR, exist_ok=True)
os.makedirs(TEST_MASK_DIR, exist_ok=True)

def create_masks_from_csv(dataset_dir, mask_dir, annotations_file="_annotations.csv"):
    os.makedirs(mask_dir, exist_ok=True)

    # Read annotations
    csv_path = os.path.join(dataset_dir, annotations_file)
    if not os.path.exists(csv_path):
        print(f"Error: Annotations file not found at {csv_path}")
        return

    annotations_df = pd.read_csv(csv_path)
    print(f"Loaded annotations with shape: {annotations_df.shape}")
    print(f"Columns in annotations file: {list(annotations_df.columns)}")

    # Extract necessary columns - modify these based on your actual CSV structure
    # Common column names in annotation CSVs include:
    try:
        if 'filename' in annotations_df.columns and 'xmin' in annotations_df.columns:
            # Format 1: separate bbox coordinates
            img_files = annotations_df['filename'].unique()

            for img_file in img_files:
                # Get image path and load image
                img_path = os.path.join(dataset_dir, img_file)
                if not os.path.exists(img_path):
                    print(f"Warning: Image {img_path} does not exist")
                    continue

                img = cv2.imread(img_path)
                if img is None:
                    print(f"Warning: Could not read image {img_path}")
                    continue

                height, width = img.shape[:2]

                # Create empty mask
                mask = np.zeros((height, width), dtype=np.uint8)

                # Get annotations for this image
                img_annots = annotations_df[annotations_df['filename'] == img_file]

                # Draw each bounding box
                for _, row in img_annots.iterrows():
                    xmin = int(row['xmin'])
                    ymin = int(row['ymin'])
                    xmax = int(row['xmax'])
                    ymax = int(row['ymax'])

                    # Make sure coordinates are valid
                    xmin = max(0, xmin)
                    ymin = max(0, ymin)
                    xmax = min(width - 1, xmax)
                    ymax = min(height - 1, ymax)

                    # Draw filled rectangle
                    cv2.rectangle(mask, (xmin, ymin), (xmax, ymax), color=255, thickness=-1)

                # Save mask
                mask_filename = os.path.splitext(img_file)[0] + ".png"
                mask_path = os.path.join(mask_dir, mask_filename)
                cv2.imwrite(mask_path, mask)

        elif 'image' in annotations_df.columns and 'bbox' in annotations_df.columns:
            # Format 2: bbox as a string like "[x, y, width, height]"
            for _, row in annotations_df.iterrows():
                img_file = row['image']

                # Get image path and load image
                img_path = os.path.join(dataset_dir, img_file)
                if not os.path.exists(img_path):
                    print(f"Warning: Image {img_path} does not exist")
                    continue

                img = cv2.imread(img_path)
                if img is None:
                    print(f"Warning: Could not read image {img_path}")
                    continue

                height, width = img.shape[:2]

                # Get or create mask
                mask_filename = os.path.splitext(img_file)[0] + ".png"
                mask_path = os.path.join(mask_dir, mask_filename)

                if os.path.exists(mask_path):
                    mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
                else:
                    mask = np.zeros((height, width), dtype=np.uint8)

                # Parse bbox
                import ast
                bbox = ast.literal_eval(row['bbox'])  # Convert string to list

                # Check if bbox format is [x, y, width, height] or [xmin, ymin, xmax, ymax]
                if len(bbox) == 4:
                    if max(bbox) <= 1.0:  # Normalized coordinates
                        if bbox[2] < 1.0 and bbox[3] < 1.0:  # [x, y, width, height]
                            xmin = int(bbox[0] * width)
                            ymin = int(bbox[1] * height)
                            box_width = int(bbox[2] * width)
                            box_height = int(bbox[3] * height)
                            xmax = xmin + box_width
                            ymax = ymin + box_height
                        else:  # [xmin, ymin, xmax, ymax]
                            xmin = int(bbox[0] * width)
                            ymin = int(bbox[1] * height)
                            xmax = int(bbox[2] * width)
                            ymax = int(bbox[3] * height)
                    else:  # Pixel coordinates
                        if bbox[2] < width/2 and bbox[3] < height/2:  # Likely [x, y, width, height]
                            xmin = int(bbox[0])
                            ymin = int(bbox[1])
                            box_width = int(bbox[2])
                            box_height = int(bbox[3])
                            xmax = xmin + box_width
                            ymax = ymin + box_height
                        else:  # [xmin, ymin, xmax, ymax]
                            xmin = int(bbox[0])
                            ymin = int(bbox[1])
                            xmax = int(bbox[2])
                            ymax = int(bbox[3])

                    # Make sure coordinates are valid
                    xmin = max(0, xmin)
                    ymin = max(0, ymin)
                    xmax = min(width - 1, xmax)
                    ymax = min(height - 1, ymax)

                    # Draw filled rectangle
                    cv2.rectangle(mask, (xmin, ymin), (xmax, ymax), color=255, thickness=-1)

                    # Save mask
                    cv2.imwrite(mask_path, mask)

        # If no matches, attempt to parse based on column names
        else:
            print("Warning: Couldn't identify standard annotation format. Attempting to parse based on column names.")

            # Try to identify columns for image filename and bounding box information
            filename_cols = [col for col in annotations_df.columns if 'file' in col.lower() or 'image' in col.lower()]
            bbox_cols = [col for col in annotations_df.columns if 'box' in col.lower() or 'bbox' in col.lower()]

            if filename_cols and bbox_cols:
                filename_col = filename_cols[0]
                bbox_col = bbox_cols[0]

                for _, row in annotations_df.iterrows():
                    img_file = str(row[filename_col])

                    # Get image path and load image
                    img_path = os.path.join(dataset_dir, img_file)
                    if not os.path.exists(img_path):
                        print(f"Warning: Image {img_path} does not exist")
                        continue

                    img = cv2.imread(img_path)
                    if img is None:
                        print(f"Warning: Could not read image {img_path}")
                        continue

                    height, width = img.shape[:2]

                    # Get or create mask
                    mask_filename = os.path.splitext(img_file)[0] + ".png"
                    mask_path = os.path.join(mask_dir, mask_filename)

                    if os.path.exists(mask_path):
                        mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
                    else:
                        mask = np.zeros((height, width), dtype=np.uint8)

                    # Try to parse bbox based on its format
                    bbox_str = str(row[bbox_col])
                    try:
                        import ast
                        bbox = ast.literal_eval(bbox_str)

                        # Similar logic to parse bbox as above
                        if isinstance(bbox, list) and len(bbox) == 4:
                            # Process bbox (same as above)
                            if max(bbox) <= 1.0:  # Normalized coordinates
                                if bbox[2] < 1.0 and bbox[3] < 1.0:  # [x, y, width, height]
                                    xmin = int(bbox[0] * width)
                                    ymin = int(bbox[1] * height)
                                    box_width = int(bbox[2] * width)
                                    box_height = int(bbox[3] * height)
                                    xmax = xmin + box_width
                                    ymax = ymin + box_height
                                else:  # [xmin, ymin, xmax, ymax]
                                    xmin = int(bbox[0] * width)
                                    ymin = int(bbox[1] * height)
                                    xmax = int(bbox[2] * width)
                                    ymax = int(bbox[3] * height)
                            else:  # Pixel coordinates
                                if bbox[2] < width/2 and bbox[3] < height/2:  # Likely [x, y, width, height]
                                    xmin = int(bbox[0])
                                    ymin = int(bbox[1])
                                    box_width = int(bbox[2])
                                    box_height = int(bbox[3])
                                    xmax = xmin + box_width
                                    ymax = ymin + box_height
                                else:  # [xmin, ymin, xmax, ymax]
                                    xmin = int(bbox[0])
                                    ymin = int(bbox[1])
                                    xmax = int(bbox[2])
                                    ymax = int(bbox[3])

                            # Make sure coordinates are valid
                            xmin = max(0, xmin)
                            ymin = max(0, ymin)
                            xmax = min(width - 1, xmax)
                            ymax = min(height - 1, ymax)

                            # Draw filled rectangle
                            cv2.rectangle(mask, (xmin, ymin), (xmax, ymax), color=255, thickness=-1)

                            # Save mask
                            cv2.imwrite(mask_path, mask)
                    except:
                        print(f"Warning: Could not parse bbox: {bbox_str}")

            else:
                print("Error: Could not identify columns for image filenames and bounding boxes.")
                print(f"Available columns: {list(annotations_df.columns)}")

    except Exception as e:
        print(f"Error processing annotations: {str(e)}")

    # Count created masks
    mask_count = len([f for f in os.listdir(mask_dir) if f.endswith('.png')])
    print(f"✅ Created {mask_count} masks in {mask_dir}")

def unet_model(input_size=(256, 256, 3)):
    inputs = Input(input_size)

    # Encoder
    c1 = Conv2D(16, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(inputs)
    c1 = BatchNormalization()(c1)
    c1 = Conv2D(16, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c1)
    c1 = BatchNormalization()(c1)
    p1 = MaxPooling2D((2, 2))(c1)

    c2 = Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(p1)
    c2 = BatchNormalization()(c2)
    c2 = Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c2)
    c2 = BatchNormalization()(c2)
    p2 = MaxPooling2D((2, 2))(c2)

    c3 = Conv2D(64, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(p2)
    c3 = BatchNormalization()(c3)
    c3 = Conv2D(64, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c3)
    c3 = BatchNormalization()(c3)
    p3 = MaxPooling2D((2, 2))(c3)

    c4 = Conv2D(128, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(p3)
    c4 = BatchNormalization()(c4)
    c4 = Conv2D(128, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c4)
    c4 = BatchNormalization()(c4)
    p4 = MaxPooling2D((2, 2))(c4)

    # Bridge
    c5 = Conv2D(256, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(p4)
    c5 = BatchNormalization()(c5)
    c5 = Conv2D(256, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c5)
    c5 = BatchNormalization()(c5)
    c5 = Dropout(0.3)(c5)

    # Decoder
    u6 = Conv2DTranspose(128, (2, 2), strides=(2, 2), padding='same')(c5)
    u6 = concatenate([u6, c4])
    c6 = Conv2D(128, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(u6)
    c6 = BatchNormalization()(c6)
    c6 = Conv2D(128, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c6)
    c6 = BatchNormalization()(c6)

    u7 = Conv2DTranspose(64, (2, 2), strides=(2, 2), padding='same')(c6)
    u7 = concatenate([u7, c3])
    c7 = Conv2D(64, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(u7)
    c7 = BatchNormalization()(c7)
    c7 = Conv2D(64, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c7)
    c7 = BatchNormalization()(c7)

    u8 = Conv2DTranspose(32, (2, 2), strides=(2, 2), padding='same')(c7)
    u8 = concatenate([u8, c2])
    c8 = Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(u8)
    c8 = BatchNormalization()(c8)
    c8 = Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c8)
    c8 = BatchNormalization()(c8)

    u9 = Conv2DTranspose(16, (2, 2), strides=(2, 2), padding='same')(c8)
    u9 = concatenate([u9, c1], axis=3)
    c9 = Conv2D(16, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(u9)
    c9 = BatchNormalization()(c9)
    c9 = Conv2D(16, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c9)
    c9 = BatchNormalization()(c9)

    outputs = Conv2D(1, (1, 1), activation='sigmoid')(c9)

    model = Model(inputs=[inputs], outputs=[outputs])
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy', tf.keras.metrics.Precision(), tf.keras.metrics.Recall()])

    return model

def load_images_and_masks(image_dir, mask_dir, img_size=(256, 256)):
    images = []
    masks = []

    # Get all image files
    img_files = [f for f in os.listdir(image_dir) if f.endswith(('.png', '.jpg', '.jpeg'))]

    for img_file in img_files:
        # Get corresponding mask file
        base_name = os.path.splitext(img_file)[0]
        mask_file = base_name + ".png"
        mask_path = os.path.join(mask_dir, mask_file)

        # Skip if mask doesn't exist
        if not os.path.exists(mask_path):
            continue

        # Read image and mask
        img_path = os.path.join(image_dir, img_file)
        img = cv2.imread(img_path)
        mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)

        if img is None or mask is None:
            continue

        # Resize
        img = cv2.resize(img, img_size)
        mask = cv2.resize(mask, img_size)

        # Normalize image and binarize mask
        img = img / 255.0
        mask = (mask > 127).astype(np.float32)

        images.append(img)
        masks.append(np.expand_dims(mask, axis=-1))

    return np.array(images), np.array(masks)

# Function to evaluate model
def evaluate_model(model, X_test, y_test, threshold=0.5):
    # Predict
    y_pred = model.predict(X_test)

    # Apply threshold
    y_pred_binary = (y_pred > threshold).astype(np.float32)

    # Flatten for metrics calculation
    y_test_flat = y_test.reshape(-1)
    y_pred_flat = y_pred_binary.reshape(-1)

    # Calculate metrics
    acc = accuracy_score(y_test_flat, y_pred_flat)
    prec = precision_score(y_test_flat, y_pred_flat, zero_division=0)
    rec = recall_score(y_test_flat, y_pred_flat, zero_division=0)
    f1 = f1_score(y_test_flat, y_pred_flat, zero_division=0)

    # Print results
    print("\nModel Evaluation Metrics:")
    print(f"Accuracy: {acc:.4f}")
    print(f"Precision: {prec:.4f}")
    print(f"Recall: {rec:.4f}")
    print(f"F1 Score: {f1:.4f}")

    return {
        'accuracy': acc,
        'precision': prec,
        'recall': rec,
        'f1_score': f1,
        'predictions': y_pred_binary,
        'raw_predictions': y_pred
    }

def plot_training_history(history):
    # Plot training & validation accuracy
    plt.figure(figsize=(12, 5))

    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'])
    plt.plot(history.history['val_accuracy'])
    plt.title('Model Accuracy')
    plt.ylabel('Accuracy')
    plt.xlabel('Epoch')
    plt.legend(['Train', 'Validation'], loc='lower right')

    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'])
    plt.plot(history.history['val_loss'])
    plt.title('Model Loss')
    plt.ylabel('Loss')
    plt.xlabel('Epoch')
    plt.legend(['Train', 'Validation'], loc='upper right')

    plt.tight_layout()
    plt.savefig('training_history.png')
    plt.show()

# Function to show prediction examples
def show_predictions(X_test, y_test, y_pred, num_examples=5):
    plt.figure(figsize=(15, 5*num_examples))

    for i in range(min(num_examples, len(X_test))):
        # Original image
        plt.subplot(num_examples, 3, i*3+1)
        plt.imshow(X_test[i])
        plt.title('Original Image')
        plt.axis('off')

        # Ground truth mask
        plt.subplot(num_examples, 3, i*3+2)
        plt.imshow(y_test[i].squeeze(), cmap='gray')
        plt.title('Ground Truth')
        plt.axis('off')

        # Predicted mask
        plt.subplot(num_examples, 3, i*3+3)
        plt.imshow(y_pred[i].squeeze(), cmap='gray')
        plt.title('Prediction')
        plt.axis('off')

    plt.tight_layout()
    plt.savefig('prediction_examples.png')
    plt.show()

if __name__ == "__main__":
    IMG_SIZE = (256, 256)
    BATCH_SIZE = 8
    EPOCHS = 30

    # Step 1: Create masks from annotations CSV
    print("Creating masks for training data...")
    create_masks_from_csv(TRAIN_DIR, TRAIN_MASK_DIR)

    print("Creating masks for test data...")
    create_masks_from_csv(TEST_DIR, TEST_MASK_DIR)

    # Step 2: Get list of all image files in the directories
    train_img_files = [f for f in os.listdir(TRAIN_DIR) if f.endswith(('.png', '.jpg', '.jpeg'))]
    test_img_files = [f for f in os.listdir(TEST_DIR) if f.endswith(('.png', '.jpg', '.jpeg'))]

    print(f"Found {len(train_img_files)} training images and {len(test_img_files)} test images")

    # Step 3: Load images and masks
    print("Loading training images and masks...")
    X_train, y_train = load_images_and_masks(TRAIN_DIR, TRAIN_MASK_DIR, IMG_SIZE)

    print("Loading test images and masks...")
    X_test, y_test = load_images_and_masks(TEST_DIR, TEST_MASK_DIR, IMG_SIZE)

    print(f"Training data shape: {X_train.shape}, {y_train.shape}")
    print(f"Test data shape: {X_test.shape}, {y_test.shape}")

    # Step 4: Split training data to get validation set
    X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

    # Step 5: Create and compile model
    model = unet_model(input_size=(*IMG_SIZE, 3))
    model.summary()

    # Step 6: Define callbacks
    callbacks = [
        ModelCheckpoint('/content/drive/MyDrive/models/unet_craters_best.h5', save_best_only=True, monitor='val_loss'),
        EarlyStopping(patience=10, restore_best_weights=True)
    ]

    # Data augmentation for training
    data_gen_args = dict(
        rotation_range=20,
        width_shift_range=0.1,
        height_shift_range=0.1,
        zoom_range=0.1,
        horizontal_flip=True,
        fill_mode='nearest'
    )

    image_datagen = ImageDataGenerator(**data_gen_args)
    mask_datagen = ImageDataGenerator(**data_gen_args)

    # Seed for reproducibility
    seed = 42

    image_generator = image_datagen.flow(X_train, batch_size=BATCH_SIZE, seed=seed)
    mask_generator = mask_datagen.flow(y_train, batch_size=BATCH_SIZE, seed=seed)

    # Combined generator
    train_generator = zip(image_generator, mask_generator)

    # Step 7: Train model
    print("Training model...")
    history = model.fit(
        X_train, y_train,
        validation_data=(X_val, y_val),
        batch_size=BATCH_SIZE,
        epochs=EPOCHS,
        callbacks=callbacks
    )

    # Step 8: Evaluate model
    print("Evaluating model...")
    model.load_weights('/content/drive/MyDrive/models/unet_craters_best.h5')  # Load best weights
    eval_results = evaluate_model(model, X_test, y_test)

    # Step 9: Plot training history
    plot_training_history(history)

    # Step 10: Show prediction examples
    show_predictions(X_test, y_test, eval_results['predictions'])

    # Save metrics to a file
    with open('model_metrics.txt', 'w') as f:
        f.write("U-Net Model Evaluation Metrics\n")
        f.write("-----------------------------\n")
        f.write(f"Accuracy: {eval_results['accuracy']:.4f}\n")
        f.write(f"Precision: {eval_results['precision']:.4f}\n")
        f.write(f"Recall: {eval_results['recall']:.4f}\n")
        f.write(f"F1 Score: {eval_results['f1_score']:.4f}\n")

    print("Complete! Model evaluation results:")
    print(f"Accuracy: {eval_results['accuracy']:.4f}")
    print(f"Precision: {eval_results['precision']:.4f}")
    print(f"Recall: {eval_results['recall']:.4f}")
    print(f"F1 Score: {eval_results['f1_score']:.4f}")